# Generated by Django 5.2.12 on 2026-03-22 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticaRetencionDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria_dato', models.CharField(choices=[('operativo', 'Operativo'), ('financiero', 'Financiero'), ('tributario', 'Tributario'), ('documental_sensible', 'Documental sensible'), ('secreto', 'Secreto')], max_length=32, unique=True)),
                ('evento_inicio', models.CharField(max_length=64)),
                ('plazo_minimo_anos', models.PositiveSmallIntegerField()),
                ('permite_borrado_logico', models.BooleanField(default=True)),
                ('permite_purga_fisica', models.BooleanField(default=False)),
                ('requiere_hold', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=16)),
            ],
            options={
                'ordering': ['categoria_dato'],
            },
        ),
        migrations.CreateModel(
            name='ExportacionSensible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria_dato', models.CharField(choices=[('operativo', 'Operativo'), ('financiero', 'Financiero'), ('tributario', 'Tributario'), ('documental_sensible', 'Documental sensible'), ('secreto', 'Secreto')], max_length=32)),
                ('export_kind', models.CharField(max_length=64)),
                ('scope_resumen', models.JSONField(blank=True, default=dict)),
                ('motivo', models.TextField()),
                ('encrypted_payload', models.TextField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('encrypted_ref', models.CharField(blank=True, max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('hold_activo', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('preparada', 'Preparada'), ('expirada', 'Expirada'), ('revocada', 'Revocada')], default='preparada', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports_sensibles_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
