# Generated by Django 5.2.12 on 2026-03-16 22:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import patrimonio.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operacion', '0001_initial'),
        ('patrimonio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrendatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_arrendatario', models.CharField(choices=[('persona_natural', 'Persona natural'), ('empresa', 'Empresa')], max_length=20)),
                ('nombre_razon_social', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=16, unique=True, validators=[patrimonio.validators.validate_rut])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('domicilio_notificaciones', models.CharField(blank=True, max_length=255)),
                ('estado_contacto', models.CharField(choices=[('pendiente', 'Pendiente'), ('activo', 'Activo'), ('inactivo', 'Inactivo')], default='pendiente', max_length=16)),
                ('whatsapp_bloqueado', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['nombre_razon_social'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo_contrato', models.CharField(max_length=64, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin_vigente', models.DateField()),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('dia_pago_mensual', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('plazo_notificacion_termino_dias', models.PositiveSmallIntegerField(default=60)),
                ('dias_prealerta_admin', models.PositiveSmallIntegerField(default=90)),
                ('estado', models.CharField(choices=[('pendiente_activacion', 'Pendiente activacion'), ('futuro', 'Futuro'), ('vigente', 'Vigente'), ('terminado_anticipadamente', 'Terminado anticipadamente'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='pendiente_activacion', max_length=32)),
                ('tiene_tramos', models.BooleanField(default=False)),
                ('tiene_gastos_comunes', models.BooleanField(default=False)),
                ('snapshot_representante_legal', models.JSONField(blank=True, default=dict)),
                ('arrendatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='contratos.arrendatario')),
                ('mandato_operacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='operacion.mandatooperacion')),
            ],
            options={
                'ordering': ['codigo_contrato'],
            },
        ),
        migrations.CreateModel(
            name='CodeudorSolidario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_identidad', models.JSONField(default=dict)),
                ('fecha_inclusion', models.DateField(default=django.utils.timezone.localdate)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=16)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codeudores_solidarios', to='contratos.contrato')),
            ],
            options={
                'ordering': ['contrato_id', 'fecha_inclusion'],
            },
        ),
        migrations.CreateModel(
            name='AvisoTermino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_efectiva', models.DateField()),
                ('causal', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('registrado', 'Registrado'), ('cancelado', 'Cancelado')], default='borrador', max_length=16)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avisos_termino_registrados', to=settings.AUTH_USER_MODEL)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos_termino', to='contratos.contrato')),
            ],
            options={
                'ordering': ['-fecha_efectiva'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'registrado')), fields=('contrato',), name='uniq_aviso_registrado_por_contrato')],
            },
        ),
        migrations.CreateModel(
            name='ContratoPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rol_en_contrato', models.CharField(choices=[('principal', 'Principal'), ('vinculada', 'Vinculada')], max_length=16)),
                ('porcentaje_distribucion_interna', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('codigo_conciliacion_efectivo_snapshot', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='El codigo de conciliacion efectivo debe tener exactamente 3 digitos.', regex='^\\d{3}$')])),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato_propiedades', to='contratos.contrato')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrato_propiedades', to='patrimonio.propiedad')),
            ],
            options={
                'ordering': ['contrato_id', 'rol_en_contrato'],
                'constraints': [models.UniqueConstraint(fields=('contrato', 'propiedad'), name='uniq_propiedad_por_contrato')],
            },
        ),
        migrations.CreateModel(
            name='PeriodoContractual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_periodo', models.PositiveSmallIntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('monto_base', models.DecimalField(decimal_places=2, max_digits=14)),
                ('moneda_base', models.CharField(choices=[('CLP', 'CLP'), ('UF', 'UF')], max_length=8)),
                ('tipo_periodo', models.CharField(max_length=64)),
                ('origen_periodo', models.CharField(max_length=64)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos_contractuales', to='contratos.contrato')),
            ],
            options={
                'ordering': ['contrato_id', 'numero_periodo'],
                'constraints': [models.UniqueConstraint(fields=('contrato', 'numero_periodo'), name='uniq_numero_periodo_por_contrato')],
            },
        ),
    ]
