# Generated by Django 5.2.12 on 2026-05-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrendatario',
            name='whatsapp_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='arrendatario',
            name='whatsapp_opt_in_evidencia_ref',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
