# Generated by Django 5.2.12 on 2026-05-24 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_arrendatario_whatsapp_opt_in_and_more'),
        ('operacion', '0003_comunidad_recaudadora'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='identidad_envio_override',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_override', to='operacion.identidaddeenvio'),
        ),
    ]
