# Generated by Django 5.2.12 on 2026-05-24

from django.db import migrations, models


def backfill_fecha_registro_operativo(apps, schema_editor):
    Contrato = apps.get_model('contratos', 'Contrato')
    queryset = (
        Contrato.objects.filter(fecha_registro_operativo__isnull=True)
        .exclude(created_at__isnull=True)
        .only('id', 'created_at', 'fecha_registro_operativo')
    )
    for contrato in queryset.iterator():
        contrato.fecha_registro_operativo = contrato.created_at.date()
        contrato.save(update_fields=['fecha_registro_operativo'])


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_contrato_identidad_envio_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='fecha_registro_operativo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_fecha_registro_operativo, migrations.RunPython.noop),
    ]
