# Generated by Django 5.2.12 on 2026-05-24 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_contrato_fecha_registro_operativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoPagoArrendatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
                ('rol_operativo', models.CharField(default='contacto_pago', max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('evidencia_autorizacion_ref', models.CharField(blank=True, max_length=255)),
                ('es_principal', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=16)),
                ('arrendatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_pago', to='contratos.arrendatario')),
            ],
            options={
                'ordering': ['arrendatario_id', '-es_principal', 'nombre'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('es_principal', True), ('estado', 'activo')), fields=('arrendatario',), name='uniq_contacto_pago_principal_activo_por_arrendatario')],
            },
        ),
    ]
