# Generated by Django 5.2.12 on 2026-05-24 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_contactopagoarrendatario'),
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='politica_documental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='documentos.politicafirmaynotaria'),
        ),
    ]
