# Generated by Django 5.2.12 on 2026-05-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0006_contrato_politica_documental'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrendatario',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('soltero', 'Soltero'), ('casado', 'Casado'), ('divorciado', 'Divorciado'), ('viudo', 'Viudo'), ('conviviente_civil', 'Conviviente civil'), ('otro', 'Otro')], max_length=32),
        ),
        migrations.AddField(
            model_name='arrendatario',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='arrendatario',
            name='profesion',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
