# Generated by Django 5.2.12 on 2026-05-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0007_arrendatario_estado_civil_arrendatario_nacionalidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrendatario',
            name='whatsapp_bloqueado_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrendatario',
            name='whatsapp_bloqueo_evidencia_ref',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='arrendatario',
            name='whatsapp_bloqueo_motivo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='arrendatario',
            name='whatsapp_rehabilitacion_ref',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='arrendatario',
            name='whatsapp_rehabilitado_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
