# Generated by Django 5.2.12 on 2026-05-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0008_arrendatario_whatsapp_bloqueado_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='terminacion_anticipada_prorrata_motivo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='terminacion_anticipada_prorrata_ref',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
