# Generated by Django 5.2.12 on 2026-05-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0009_contrato_terminacion_anticipada_prorrata_motivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avisotermino',
            name='resolucion_conflicto_renovacion_motivo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='avisotermino',
            name='resolucion_conflicto_renovacion_ref',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
