# Generated by Django 5.2.12 on 2026-05-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0010_avisotermino_resolucion_conflicto_renovacion_motivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodocontractual',
            name='politica_base_renovacion_motivo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='periodocontractual',
            name='politica_base_renovacion_ref',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
