# Generated by Django 5.2.12 on 2026-05-29 10:32

from django.db import migrations, models


def backfill_registrado_at(apps, schema_editor):
    aviso_termino = apps.get_model('contratos', 'AvisoTermino')
    (
        aviso_termino.objects.filter(estado='registrado', registrado_at__isnull=True)
        .update(registrado_at=models.F('created_at'))
    )


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0012_contrato_entrega_llaves_autorizacion_motivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avisotermino',
            name='registrado_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_registrado_at, migrations.RunPython.noop),
    ]
