# Generated by Django 5.2.12 on 2026-03-17 20:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cobranza', '0002_codigocobroresidual_estadocuentaarrendatario_and_more'),
        ('operacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConexionBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_key', models.CharField(max_length=64)),
                ('credencial_ref', models.CharField(max_length=255)),
                ('scope', models.CharField(blank=True, max_length=255)),
                ('expira_en', models.DateTimeField(blank=True, null=True)),
                ('estado_conexion', models.CharField(choices=[('verificando', 'Verificando'), ('activa', 'Activa'), ('pausada', 'Pausada'), ('inactiva', 'Inactiva')], default='verificando', max_length=16)),
                ('primaria_movimientos', models.BooleanField(default=False)),
                ('primaria_saldos', models.BooleanField(default=False)),
                ('primaria_conectividad', models.BooleanField(default=False)),
                ('ultimo_exito_at', models.DateTimeField(blank=True, null=True)),
                ('ultimo_error_at', models.DateTimeField(blank=True, null=True)),
                ('cuenta_recaudadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexiones_bancarias', to='operacion.cuentarecaudadora')),
            ],
            options={
                'ordering': ['cuenta_recaudadora_id', 'provider_key'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoBancarioImportado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_movimiento', models.DateField()),
                ('tipo_movimiento', models.CharField(choices=[('abono', 'Abono'), ('cargo', 'Cargo')], max_length=8)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('descripcion_origen', models.TextField()),
                ('numero_documento', models.CharField(blank=True, max_length=64)),
                ('saldo_reportado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('referencia', models.CharField(blank=True, max_length=255)),
                ('transaction_id_banco', models.CharField(blank=True, max_length=255)),
                ('estado_conciliacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('conciliado_exacto', 'Conciliado exacto'), ('ingreso_desconocido', 'Ingreso desconocido'), ('manual_requerida', 'Manual requerida')], default='pendiente', max_length=24)),
                ('notas_admin', models.TextField(blank=True)),
                ('codigo_cobro_residual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_bancarios', to='cobranza.codigocobroresidual')),
                ('conexion_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_importados', to='conciliacion.conexionbancaria')),
                ('pago_mensual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_bancarios', to='cobranza.pagomensual')),
            ],
            options={
                'ordering': ['-fecha_movimiento', '-id'],
            },
        ),
        migrations.CreateModel(
            name='IngresoDesconocido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha_movimiento', models.DateField()),
                ('descripcion_origen', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente_revision', 'Pendiente revision'), ('resuelto', 'Resuelto'), ('descartado', 'Descartado')], default='pendiente_revision', max_length=24)),
                ('sugerencia_asistida', models.JSONField(blank=True, default=dict)),
                ('cuenta_recaudadora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos_desconocidos', to='operacion.cuentarecaudadora')),
                ('movimiento_bancario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ingreso_desconocido', to='conciliacion.movimientobancarioimportado')),
            ],
            options={
                'ordering': ['-fecha_movimiento', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='conexionbancaria',
            constraint=models.UniqueConstraint(fields=('cuenta_recaudadora', 'provider_key'), name='uniq_provider_por_cuenta_recaudadora'),
        ),
        migrations.AddConstraint(
            model_name='conexionbancaria',
            constraint=models.UniqueConstraint(condition=models.Q(('primaria_movimientos', True)), fields=('cuenta_recaudadora',), name='uniq_primaria_movimientos_por_cuenta'),
        ),
        migrations.AddConstraint(
            model_name='conexionbancaria',
            constraint=models.UniqueConstraint(condition=models.Q(('primaria_saldos', True)), fields=('cuenta_recaudadora',), name='uniq_primaria_saldos_por_cuenta'),
        ),
        migrations.AddConstraint(
            model_name='conexionbancaria',
            constraint=models.UniqueConstraint(condition=models.Q(('primaria_conectividad', True)), fields=('cuenta_recaudadora',), name='uniq_primaria_conectividad_por_cuenta'),
        ),
        migrations.AddConstraint(
            model_name='movimientobancarioimportado',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('codigo_cobro_residual__isnull', True), ('pago_mensual__isnull', False)), models.Q(('codigo_cobro_residual__isnull', False), ('pago_mensual__isnull', True)), models.Q(('codigo_cobro_residual__isnull', True), ('pago_mensual__isnull', True)), _connector='OR'), name='movimiento_exactly_one_match_target'),
        ),
    ]
