# Generated by Django 5.2.12 on 2026-05-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conciliacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conexionbancaria',
            name='evidencia_gate_ref',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='conexionbancaria',
            name='prueba_conectividad_ref',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='conexionbancaria',
            name='prueba_movimientos_ref',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='conexionbancaria',
            name='prueba_saldos_ref',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='movimientobancarioimportado',
            name='evidencia_importacion_ref',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='movimientobancarioimportado',
            name='origen_importacion',
            field=models.CharField(choices=[('manual_controlada', 'Manual controlada'), ('provider_sync', 'Provider sync')], default='manual_controlada', max_length=24),
        ),
    ]
