# Generated by Django 5.2.12 on 2026-05-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0006_pagomensual_fecha_pago_webpay_gatecobroexterno_and_more'),
        ('conciliacion', '0002_conexionbancaria_evidencia_gate_ref_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='movimientobancarioimportado',
            constraint=models.UniqueConstraint(condition=models.Q(('transaction_id_banco', ''), _negated=True), fields=('conexion_bancaria', 'transaction_id_banco'), name='uniq_transaction_id_banco_por_conexion'),
        ),
    ]
