# Generated by Django 5.2.12 on 2026-05-24 08:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conciliacion', '0003_unique_bank_transaction_id'),
        ('operacion', '0003_comunidad_recaudadora'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuadraturaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('periodo_economico', models.CharField(max_length=7)),
                ('fecha_cuadratura', models.DateField()),
                ('saldo_sistema_clp', models.DecimalField(decimal_places=2, max_digits=14)),
                ('saldo_banco_clp', models.DecimalField(decimal_places=2, max_digits=14)),
                ('diferencia_clp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('estado', models.CharField(choices=[('cuadrada', 'Cuadrada'), ('diferencia_abierta', 'Diferencia abierta'), ('diferencia_explicada', 'Diferencia explicada')], default='cuadrada', max_length=24)),
                ('evidencia_cuadratura_ref', models.CharField(max_length=255)),
                ('responsable_ref', models.CharField(max_length=255)),
                ('rationale', models.TextField(blank=True)),
                ('cuenta_recaudadora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuadraturas_bancarias', to='operacion.cuentarecaudadora')),
            ],
            options={
                'ordering': ['-periodo_economico', '-fecha_cuadratura', '-id'],
                'constraints': [models.UniqueConstraint(fields=('cuenta_recaudadora', 'periodo_economico'), name='uniq_cuadratura_bancaria_por_cuenta_periodo')],
            },
        ),
    ]
