# Generated by Codex on 2026-05-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conciliacion', '0004_cuadraturabancaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferenciaIntercuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('periodo_economico', models.CharField(max_length=7)),
                ('entidad_origen_tipo', models.CharField(blank=True, max_length=16)),
                ('entidad_origen_id', models.PositiveIntegerField(blank=True, null=True)),
                ('entidad_destino_tipo', models.CharField(blank=True, max_length=16)),
                ('entidad_destino_id', models.PositiveIntegerField(blank=True, null=True)),
                ('criterio_conciliacion', models.CharField(max_length=255)),
                ('evidencia_transferencia_ref', models.CharField(max_length=255)),
                ('responsable_ref', models.CharField(max_length=255)),
                ('rationale', models.TextField()),
                (
                    'movimiento_destino',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='transferencias_intercuenta_destino',
                        to='conciliacion.movimientobancarioimportado',
                    ),
                ),
                (
                    'movimiento_origen',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='transferencias_intercuenta_origen',
                        to='conciliacion.movimientobancarioimportado',
                    ),
                ),
            ],
            options={
                'ordering': ['-periodo_economico', '-id'],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('movimiento_origen',),
                        name='uniq_transferencia_intercuenta_origen',
                    ),
                    models.UniqueConstraint(
                        fields=('movimiento_destino',),
                        name='uniq_transferencia_intercuenta_destino',
                    ),
                    models.UniqueConstraint(
                        fields=('movimiento_origen', 'movimiento_destino'),
                        name='uniq_transferencia_intercuenta_par_movimientos',
                    ),
                ],
            },
        ),
    ]
