# Generated by Django 5.2.12 on 2026-03-16 18:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import patrimonio.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=16, unique=True, validators=[patrimonio.validators.validate_rut])),
                ('domicilio', models.CharField(blank=True, max_length=255)),
                ('giro', models.CharField(blank=True, max_length=255)),
                ('codigo_actividad_sii', models.CharField(blank=True, max_length=32)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('inactiva', 'Inactiva')], default='borrador', max_length=16)),
            ],
            options={
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=16, unique=True, validators=[patrimonio.validators.validate_rut])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('domicilio', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ComunidadPatrimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('inactiva', 'Inactiva')], default='borrador', max_length=16)),
                ('representante_socio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comunidades_representadas', to='patrimonio.socio')),
            ],
            options={
                'verbose_name_plural': 'comunidades patrimoniales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rol_avaluo', models.CharField(blank=True, max_length=64)),
                ('direccion', models.CharField(max_length=255)),
                ('comuna', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('tipo_inmueble', models.CharField(choices=[('departamento', 'Departamento'), ('casa', 'Casa'), ('local', 'Local'), ('oficina', 'Oficina'), ('bodega', 'Bodega'), ('estacionamiento', 'Estacionamiento'), ('otro', 'Otro')], max_length=32)),
                ('codigo_propiedad', models.CharField(max_length=16)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('inactiva', 'Inactiva')], default='borrador', max_length=16)),
                ('comunidad_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propiedades', to='patrimonio.comunidadpatrimonial')),
                ('empresa_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propiedades', to='patrimonio.empresa')),
                ('socio_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propiedades_directas', to='patrimonio.socio')),
            ],
            options={
                'ordering': ['codigo_propiedad', 'direccion'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('comunidad_owner__isnull', True), ('empresa_owner__isnull', False), ('socio_owner__isnull', True)), models.Q(('comunidad_owner__isnull', False), ('empresa_owner__isnull', True), ('socio_owner__isnull', True)), models.Q(('comunidad_owner__isnull', True), ('empresa_owner__isnull', True), ('socio_owner__isnull', False)), _connector='OR'), name='propiedad_exactly_one_owner'), models.UniqueConstraint(condition=models.Q(('empresa_owner__isnull', False)), fields=('codigo_propiedad', 'empresa_owner'), name='uniq_codigo_propiedad_por_empresa'), models.UniqueConstraint(condition=models.Q(('comunidad_owner__isnull', False)), fields=('codigo_propiedad', 'comunidad_owner'), name='uniq_codigo_propiedad_por_comunidad'), models.UniqueConstraint(condition=models.Q(('socio_owner__isnull', False)), fields=('codigo_propiedad', 'socio_owner'), name='uniq_codigo_propiedad_por_socio')],
            },
        ),
        migrations.CreateModel(
            name='ParticipacionPatrimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('vigente_desde', models.DateField(default=django.utils.timezone.localdate)),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('comunidad_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='patrimonio.comunidadpatrimonial')),
                ('empresa_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='patrimonio.empresa')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participaciones_patrimoniales', to='patrimonio.socio')),
            ],
            options={
                'ordering': ['socio__nombre', '-vigente_desde'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('comunidad_owner__isnull', True), ('empresa_owner__isnull', False)), models.Q(('comunidad_owner__isnull', False), ('empresa_owner__isnull', True)), _connector='OR'), name='participacion_exactly_one_owner')],
            },
        ),
    ]
