# Generated by Django 5.2.12 on 2026-05-24 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0003_repair_legacy_representacion_modes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_servicio', models.CharField(choices=[('gasto_comun', 'Gasto comun'), ('electricidad', 'Electricidad'), ('agua', 'Agua'), ('gas', 'Gas'), ('internet', 'Internet'), ('mantencion', 'Mantencion'), ('otro', 'Otro')], max_length=32)),
                ('proveedor_nombre', models.CharField(blank=True, max_length=255)),
                ('numero_cliente', models.CharField(blank=True, max_length=80)),
                ('administrador_nombre', models.CharField(blank=True, max_length=255)),
                ('evidencia_ref', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='patrimonio.propiedad')),
            ],
            options={
                'ordering': ['propiedad_id', 'tipo_servicio', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True), ('tipo_servicio', 'gasto_comun')), fields=('propiedad',), name='uniq_gasto_comun_activo_por_propiedad')],
            },
        ),
    ]
