# Generated by Django 5.2.12 on 2026-03-18 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
        ('documentos', '0001_initial'),
        ('operacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalMensajeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canal', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=16, unique=True)),
                ('provider_key', models.CharField(max_length=64)),
                ('estado_gate', models.CharField(choices=[('abierto', 'Abierto'), ('condicionado', 'Condicionado'), ('cerrado', 'Cerrado'), ('suspendido', 'Suspendido')], default='condicionado', max_length=16)),
                ('restricciones_operativas', models.JSONField(blank=True, default=dict)),
                ('evidencia_ref', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['canal'],
            },
        ),
        migrations.CreateModel(
            name='MensajeSaliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canal', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=16)),
                ('destinatario', models.CharField(blank=True, max_length=255)),
                ('asunto', models.CharField(blank=True, max_length=255)),
                ('cuerpo', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('preparado', 'Preparado'), ('bloqueado', 'Bloqueado'), ('enviado', 'Enviado'), ('fallido', 'Fallido')], default='borrador', max_length=16)),
                ('motivo_bloqueo', models.TextField(blank=True)),
                ('external_ref', models.CharField(blank=True, max_length=255)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('enviado_at', models.DateTimeField(blank=True, null=True)),
                ('arrendatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mensajes_salientes', to='contratos.arrendatario')),
                ('canal_mensajeria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensajes_salientes', to='canales.canalmensajeria')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mensajes_salientes', to='contratos.contrato')),
                ('documento_emitido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mensajes_salientes', to='documentos.documentoemitido')),
                ('identidad_envio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mensajes_salientes', to='operacion.identidaddeenvio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_salientes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('contrato__isnull', False), ('arrendatario__isnull', False), ('documento_emitido__isnull', False), _connector='OR'), name='mensaje_requiere_contexto')],
            },
        ),
    ]
