# Generated by Django 5.2.12 on 2026-05-24 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canales', '0001_initial'),
        ('contratos', '0008_arrendatario_whatsapp_bloqueado_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionNotificacionContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canal', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=16)),
                ('dias_notificacion', models.JSONField(blank=True, default=list)),
                ('activa', models.BooleanField(default=True)),
                ('evidencia_configuracion_ref', models.CharField(blank=True, max_length=255)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_notificacion', to='contratos.contrato')),
            ],
            options={
                'ordering': ['contrato_id', 'canal', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('contrato', 'canal'), name='uniq_config_notificacion_activa_por_contrato_canal')],
            },
        ),
    ]
