# Generated by Codex on 2026-05-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canales', '0002_configuracionnotificacioncontrato'),
        ('cobranza', '0007_garantiacontractual_aceptacion_parcial_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionCobranzaProgramada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canal', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=16)),
                ('dia_notificacion', models.PositiveSmallIntegerField()),
                ('fecha_programada', models.DateField()),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('preparada', 'Preparada'), ('omitida', 'Omitida')], default='programada', max_length=16)),
                ('motivo_estado', models.TextField(blank=True)),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_programadas', to='canales.configuracionnotificacioncontrato')),
                ('mensaje_saliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_cobranza', to='canales.mensajesaliente')),
                ('pago_mensual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_cobranza', to='cobranza.pagomensual')),
            ],
            options={
                'ordering': ['fecha_programada', 'pago_mensual_id', 'canal', 'dia_notificacion'],
                'constraints': [models.UniqueConstraint(fields=('pago_mensual', 'canal', 'dia_notificacion'), name='uniq_notificacion_cobranza_por_pago_canal_dia')],
            },
        ),
    ]
