from django.urls import path

from .views import (
    AnnualEnterpriseRegisterMovementDetailView,
    AnnualEnterpriseRegisterMovementListView,
    AnnualEnterpriseRegisterSetDetailView,
    AnnualEnterpriseRegisterSetListView,
    AnnualRealEstateItemDetailView,
    AnnualRealEstateItemListView,
    AnnualRealEstateSectionDetailView,
    AnnualRealEstateSectionListView,
    AnnualGenerateView,
    AnnualTaxArtifactMatrixDetailView,
    AnnualTaxArtifactMatrixItemDetailView,
    AnnualTaxArtifactMatrixItemListView,
    AnnualTaxArtifactMatrixListView,
    AnnualTaxDDJJFormLayoutDetailView,
    AnnualTaxDDJJFormLayoutListCreateView,
    AnnualTaxF22ExportLayoutDetailView,
    AnnualTaxF22ExportLayoutListCreateView,
    AnnualTaxDossierDetailView,
    AnnualTaxDossierListView,
    AnnualTaxExportDetailView,
    AnnualTaxExportListView,
    AnnualTaxOfficialSourceDetailView,
    AnnualTaxOfficialSourceListCreateView,
    AnnualTaxReviewDecisionUpdateView,
    AnnualTaxReviewChecklistDetailView,
    AnnualTaxReviewChecklistListView,
    AnnualTaxSourceBundleDetailView,
    AnnualTaxSourceBundleListCreateView,
    AnnualTaxTrialBalanceDetailView,
    AnnualTaxTrialBalanceLineDetailView,
    AnnualTaxTrialBalanceLineListView,
    AnnualTaxTrialBalanceListView,
    AnnualTaxWorkbookDetailView,
    AnnualTaxWorkbookLineDetailView,
    AnnualTaxWorkbookLineListView,
    AnnualTaxWorkbookListView,
    CapacidadTributariaSIIDetailView,
    CapacidadTributariaSIIListCreateView,
    DDJJPreparacionAnualListView,
    DDJJStatusUpdateView,
    DTEEmitidoDetailView,
    DTEEmitidoListView,
    DTEGenerateView,
    DTEStatusUpdateView,
    F22PreparacionAnualListView,
    F22StatusUpdateView,
    F29GenerateView,
    F29PreparacionDetailView,
    F29PreparacionListView,
    F29StatusUpdateView,
    MonthlyTaxFactDetailView,
    MonthlyTaxFactListView,
    ProcesoRentaAnualListView,
    SiiSnapshotView,
    TaxCodeMappingDetailView,
    TaxCodeMappingListCreateView,
    TaxYearRuleSetDetailView,
    TaxYearRuleSetListCreateView,
)

urlpatterns = [
    path('snapshot/', SiiSnapshotView.as_view(), name='sii-snapshot'),
    path('capacidades/', CapacidadTributariaSIIListCreateView.as_view(), name='sii-capacidad-list'),
    path('capacidades/<int:pk>/', CapacidadTributariaSIIDetailView.as_view(), name='sii-capacidad-detail'),
    path('anual/rule-sets/', TaxYearRuleSetListCreateView.as_view(), name='sii-tax-year-ruleset-list'),
    path('anual/rule-sets/<int:pk>/', TaxYearRuleSetDetailView.as_view(), name='sii-tax-year-ruleset-detail'),
    path('anual/code-mappings/', TaxCodeMappingListCreateView.as_view(), name='sii-tax-code-mapping-list'),
    path('anual/code-mappings/<int:pk>/', TaxCodeMappingDetailView.as_view(), name='sii-tax-code-mapping-detail'),
    path('anual/official-sources/', AnnualTaxOfficialSourceListCreateView.as_view(), name='sii-annual-tax-official-source-list'),
    path('anual/official-sources/<int:pk>/', AnnualTaxOfficialSourceDetailView.as_view(), name='sii-annual-tax-official-source-detail'),
    path('anual/ddjj-layouts/', AnnualTaxDDJJFormLayoutListCreateView.as_view(), name='sii-annual-tax-ddjj-layout-list'),
    path('anual/ddjj-layouts/<int:pk>/', AnnualTaxDDJJFormLayoutDetailView.as_view(), name='sii-annual-tax-ddjj-layout-detail'),
    path('anual/f22-export-layouts/', AnnualTaxF22ExportLayoutListCreateView.as_view(), name='sii-annual-tax-f22-export-layout-list'),
    path('anual/f22-export-layouts/<int:pk>/', AnnualTaxF22ExportLayoutDetailView.as_view(), name='sii-annual-tax-f22-export-layout-detail'),
    path('anual/source-bundles/', AnnualTaxSourceBundleListCreateView.as_view(), name='sii-annual-source-bundle-list'),
    path('anual/source-bundles/<int:pk>/', AnnualTaxSourceBundleDetailView.as_view(), name='sii-annual-source-bundle-detail'),
    path('anual/monthly-facts/', MonthlyTaxFactListView.as_view(), name='sii-monthly-tax-fact-list'),
    path('anual/monthly-facts/<int:pk>/', MonthlyTaxFactDetailView.as_view(), name='sii-monthly-tax-fact-detail'),
    path('anual/trial-balances/', AnnualTaxTrialBalanceListView.as_view(), name='sii-annual-tax-trial-balance-list'),
    path('anual/trial-balances/<int:pk>/', AnnualTaxTrialBalanceDetailView.as_view(), name='sii-annual-tax-trial-balance-detail'),
    path('anual/trial-balance-lines/', AnnualTaxTrialBalanceLineListView.as_view(), name='sii-annual-tax-trial-balance-line-list'),
    path('anual/trial-balance-lines/<int:pk>/', AnnualTaxTrialBalanceLineDetailView.as_view(), name='sii-annual-tax-trial-balance-line-detail'),
    path('anual/workbooks/', AnnualTaxWorkbookListView.as_view(), name='sii-annual-tax-workbook-list'),
    path('anual/workbooks/<int:pk>/', AnnualTaxWorkbookDetailView.as_view(), name='sii-annual-tax-workbook-detail'),
    path('anual/workbook-lines/', AnnualTaxWorkbookLineListView.as_view(), name='sii-annual-tax-workbook-line-list'),
    path('anual/workbook-lines/<int:pk>/', AnnualTaxWorkbookLineDetailView.as_view(), name='sii-annual-tax-workbook-line-detail'),
    path('anual/enterprise-registers/', AnnualEnterpriseRegisterSetListView.as_view(), name='sii-annual-enterprise-register-list'),
    path('anual/enterprise-registers/<int:pk>/', AnnualEnterpriseRegisterSetDetailView.as_view(), name='sii-annual-enterprise-register-detail'),
    path('anual/enterprise-register-movements/', AnnualEnterpriseRegisterMovementListView.as_view(), name='sii-annual-enterprise-register-movement-list'),
    path('anual/enterprise-register-movements/<int:pk>/', AnnualEnterpriseRegisterMovementDetailView.as_view(), name='sii-annual-enterprise-register-movement-detail'),
    path('anual/real-estate-sections/', AnnualRealEstateSectionListView.as_view(), name='sii-annual-real-estate-section-list'),
    path('anual/real-estate-sections/<int:pk>/', AnnualRealEstateSectionDetailView.as_view(), name='sii-annual-real-estate-section-detail'),
    path('anual/real-estate-items/', AnnualRealEstateItemListView.as_view(), name='sii-annual-real-estate-item-list'),
    path('anual/real-estate-items/<int:pk>/', AnnualRealEstateItemDetailView.as_view(), name='sii-annual-real-estate-item-detail'),
    path('anual/artifact-matrices/', AnnualTaxArtifactMatrixListView.as_view(), name='sii-annual-tax-artifact-matrix-list'),
    path('anual/artifact-matrices/<int:pk>/', AnnualTaxArtifactMatrixDetailView.as_view(), name='sii-annual-tax-artifact-matrix-detail'),
    path('anual/artifact-matrix-items/', AnnualTaxArtifactMatrixItemListView.as_view(), name='sii-annual-tax-artifact-matrix-item-list'),
    path('anual/artifact-matrix-items/<int:pk>/', AnnualTaxArtifactMatrixItemDetailView.as_view(), name='sii-annual-tax-artifact-matrix-item-detail'),
    path('anual/dossiers/', AnnualTaxDossierListView.as_view(), name='sii-annual-tax-dossier-list'),
    path('anual/dossiers/<int:pk>/', AnnualTaxDossierDetailView.as_view(), name='sii-annual-tax-dossier-detail'),
    path('anual/exports/', AnnualTaxExportListView.as_view(), name='sii-annual-tax-export-list'),
    path('anual/exports/<int:pk>/', AnnualTaxExportDetailView.as_view(), name='sii-annual-tax-export-detail'),
    path('anual/review-checklists/', AnnualTaxReviewChecklistListView.as_view(), name='sii-annual-tax-review-checklist-list'),
    path('anual/review-checklists/<int:pk>/', AnnualTaxReviewChecklistDetailView.as_view(), name='sii-annual-tax-review-checklist-detail'),
    path('anual/review-checklists/<int:pk>/decision/', AnnualTaxReviewDecisionUpdateView.as_view(), name='sii-annual-tax-review-checklist-decision'),
    path('dtes/', DTEEmitidoListView.as_view(), name='sii-dte-list'),
    path('dtes/<int:pk>/', DTEEmitidoDetailView.as_view(), name='sii-dte-detail'),
    path('dtes/generar/', DTEGenerateView.as_view(), name='sii-dte-generate'),
    path('dtes/<int:pk>/estado/', DTEStatusUpdateView.as_view(), name='sii-dte-status'),
    path('f29/', F29PreparacionListView.as_view(), name='sii-f29-list'),
    path('f29/<int:pk>/', F29PreparacionDetailView.as_view(), name='sii-f29-detail'),
    path('f29/generar/', F29GenerateView.as_view(), name='sii-f29-generate'),
    path('f29/<int:pk>/estado/', F29StatusUpdateView.as_view(), name='sii-f29-status'),
    path('anual/', ProcesoRentaAnualListView.as_view(), name='sii-anual-list'),
    path('anual/generar/', AnnualGenerateView.as_view(), name='sii-anual-generate'),
    path('anual/ddjj/', DDJJPreparacionAnualListView.as_view(), name='sii-ddjj-list'),
    path('anual/ddjj/<int:pk>/estado/', DDJJStatusUpdateView.as_view(), name='sii-ddjj-status'),
    path('anual/f22/', F22PreparacionAnualListView.as_view(), name='sii-f22-list'),
    path('anual/f22/<int:pk>/estado/', F22StatusUpdateView.as_view(), name='sii-f22-status'),
]
