from django.urls import path

from .views import (
    AnnualEnterpriseRegisterMovementDetailView,
    AnnualEnterpriseRegisterMovementListView,
    AnnualEnterpriseRegisterSetDetailView,
    AnnualEnterpriseRegisterSetListView,
    AnnualRealEstateItemDetailView,
    AnnualRealEstateItemListView,
    AnnualRealEstateSectionDetailView,
    AnnualRealEstateSectionListView,
    AnnualGenerateView,
    AnnualTaxSourceBundleDetailView,
    AnnualTaxSourceBundleListCreateView,
    AnnualTaxWorkbookDetailView,
    AnnualTaxWorkbookLineDetailView,
    AnnualTaxWorkbookLineListView,
    AnnualTaxWorkbookListView,
    CapacidadTributariaSIIDetailView,
    CapacidadTributariaSIIListCreateView,
    DDJJPreparacionAnualListView,
    DDJJStatusUpdateView,
    DTEEmitidoDetailView,
    DTEEmitidoListView,
    DTEGenerateView,
    DTEStatusUpdateView,
    F22PreparacionAnualListView,
    F22StatusUpdateView,
    F29GenerateView,
    F29PreparacionDetailView,
    F29PreparacionListView,
    F29StatusUpdateView,
    MonthlyTaxFactDetailView,
    MonthlyTaxFactListView,
    ProcesoRentaAnualListView,
    SiiSnapshotView,
    TaxCodeMappingDetailView,
    TaxCodeMappingListCreateView,
    TaxYearRuleSetDetailView,
    TaxYearRuleSetListCreateView,
)

urlpatterns = [
    path('snapshot/', SiiSnapshotView.as_view(), name='sii-snapshot'),
    path('capacidades/', CapacidadTributariaSIIListCreateView.as_view(), name='sii-capacidad-list'),
    path('capacidades/<int:pk>/', CapacidadTributariaSIIDetailView.as_view(), name='sii-capacidad-detail'),
    path('anual/rule-sets/', TaxYearRuleSetListCreateView.as_view(), name='sii-tax-year-ruleset-list'),
    path('anual/rule-sets/<int:pk>/', TaxYearRuleSetDetailView.as_view(), name='sii-tax-year-ruleset-detail'),
    path('anual/code-mappings/', TaxCodeMappingListCreateView.as_view(), name='sii-tax-code-mapping-list'),
    path('anual/code-mappings/<int:pk>/', TaxCodeMappingDetailView.as_view(), name='sii-tax-code-mapping-detail'),
    path('anual/source-bundles/', AnnualTaxSourceBundleListCreateView.as_view(), name='sii-annual-source-bundle-list'),
    path('anual/source-bundles/<int:pk>/', AnnualTaxSourceBundleDetailView.as_view(), name='sii-annual-source-bundle-detail'),
    path('anual/monthly-facts/', MonthlyTaxFactListView.as_view(), name='sii-monthly-tax-fact-list'),
    path('anual/monthly-facts/<int:pk>/', MonthlyTaxFactDetailView.as_view(), name='sii-monthly-tax-fact-detail'),
    path('anual/workbooks/', AnnualTaxWorkbookListView.as_view(), name='sii-annual-tax-workbook-list'),
    path('anual/workbooks/<int:pk>/', AnnualTaxWorkbookDetailView.as_view(), name='sii-annual-tax-workbook-detail'),
    path('anual/workbook-lines/', AnnualTaxWorkbookLineListView.as_view(), name='sii-annual-tax-workbook-line-list'),
    path('anual/workbook-lines/<int:pk>/', AnnualTaxWorkbookLineDetailView.as_view(), name='sii-annual-tax-workbook-line-detail'),
    path('anual/enterprise-registers/', AnnualEnterpriseRegisterSetListView.as_view(), name='sii-annual-enterprise-register-list'),
    path('anual/enterprise-registers/<int:pk>/', AnnualEnterpriseRegisterSetDetailView.as_view(), name='sii-annual-enterprise-register-detail'),
    path('anual/enterprise-register-movements/', AnnualEnterpriseRegisterMovementListView.as_view(), name='sii-annual-enterprise-register-movement-list'),
    path('anual/enterprise-register-movements/<int:pk>/', AnnualEnterpriseRegisterMovementDetailView.as_view(), name='sii-annual-enterprise-register-movement-detail'),
    path('anual/real-estate-sections/', AnnualRealEstateSectionListView.as_view(), name='sii-annual-real-estate-section-list'),
    path('anual/real-estate-sections/<int:pk>/', AnnualRealEstateSectionDetailView.as_view(), name='sii-annual-real-estate-section-detail'),
    path('anual/real-estate-items/', AnnualRealEstateItemListView.as_view(), name='sii-annual-real-estate-item-list'),
    path('anual/real-estate-items/<int:pk>/', AnnualRealEstateItemDetailView.as_view(), name='sii-annual-real-estate-item-detail'),
    path('dtes/', DTEEmitidoListView.as_view(), name='sii-dte-list'),
    path('dtes/<int:pk>/', DTEEmitidoDetailView.as_view(), name='sii-dte-detail'),
    path('dtes/generar/', DTEGenerateView.as_view(), name='sii-dte-generate'),
    path('dtes/<int:pk>/estado/', DTEStatusUpdateView.as_view(), name='sii-dte-status'),
    path('f29/', F29PreparacionListView.as_view(), name='sii-f29-list'),
    path('f29/<int:pk>/', F29PreparacionDetailView.as_view(), name='sii-f29-detail'),
    path('f29/generar/', F29GenerateView.as_view(), name='sii-f29-generate'),
    path('f29/<int:pk>/estado/', F29StatusUpdateView.as_view(), name='sii-f29-status'),
    path('anual/', ProcesoRentaAnualListView.as_view(), name='sii-anual-list'),
    path('anual/generar/', AnnualGenerateView.as_view(), name='sii-anual-generate'),
    path('anual/ddjj/', DDJJPreparacionAnualListView.as_view(), name='sii-ddjj-list'),
    path('anual/ddjj/<int:pk>/estado/', DDJJStatusUpdateView.as_view(), name='sii-ddjj-status'),
    path('anual/f22/', F22PreparacionAnualListView.as_view(), name='sii-f22-list'),
    path('anual/f22/<int:pk>/estado/', F22StatusUpdateView.as_view(), name='sii-f22-status'),
]
