# Generated by Django 5.2.12 on 2026-03-18 04:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patrimonio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegimenTributarioEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo_regimen', models.CharField(max_length=64, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=16)),
            ],
            options={
                'ordering': ['codigo_regimen'],
            },
        ),
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_cuentas_version', models.CharField(max_length=32)),
                ('codigo', models.CharField(max_length=32)),
                ('nombre', models.CharField(max_length=255)),
                ('naturaleza', models.CharField(choices=[('deudora', 'Deudora'), ('acreedora', 'Acreedora')], max_length=16)),
                ('nivel', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=16)),
                ('es_control_obligatoria', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_contables', to='patrimonio.empresa')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcuentas', to='contabilidad.cuentacontable')),
            ],
            options={
                'ordering': ['empresa_id', 'plan_cuentas_version', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='EventoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evento_tipo', models.CharField(max_length=64)),
                ('entidad_origen_tipo', models.CharField(max_length=64)),
                ('entidad_origen_id', models.CharField(max_length=64)),
                ('fecha_operativa', models.DateField()),
                ('moneda', models.CharField(choices=[('CLP', 'CLP'), ('UF', 'UF')], default='CLP', max_length=8)),
                ('monto_base', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payload_resumen', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('estado_contable', models.CharField(choices=[('pendiente_contabilizacion', 'Pendiente contabilizacion'), ('pendiente_revision_contable', 'Pendiente revision contable'), ('contabilizado', 'Contabilizado')], default='pendiente_contabilizacion', max_length=32)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_contables', to='patrimonio.empresa')),
            ],
            options={
                'ordering': ['-fecha_operativa', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AsientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_contable', models.DateField()),
                ('periodo_contable', models.CharField(max_length=7)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('contabilizado', 'Contabilizado'), ('revertido', 'Revertido')], default='contabilizado', max_length=16)),
                ('debe_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('haber_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('moneda_funcional', models.CharField(choices=[('CLP', 'CLP'), ('UF', 'UF')], default='CLP', max_length=8)),
                ('hash_integridad', models.CharField(blank=True, max_length=64)),
                ('evento_contable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asiento_contable', to='contabilidad.eventocontable')),
            ],
            options={
                'ordering': ['-fecha_contable', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoAsiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_movimiento', models.CharField(choices=[('debe', 'Debe'), ('haber', 'Haber')], max_length=8)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('glosa', models.CharField(blank=True, max_length=255)),
                ('centro_resultado_ref', models.CharField(blank=True, max_length=64)),
                ('asiento_contable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='contabilidad.asientocontable')),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='contabilidad.cuentacontable')),
            ],
            options={
                'ordering': ['asiento_contable_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionFiscalEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('afecta_iva_arriendo', models.BooleanField(default=False)),
                ('tasa_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('aplica_ppm', models.BooleanField(default=False)),
                ('ddjj_habilitadas', models.JSONField(blank=True, default=list)),
                ('inicio_ejercicio', models.DateField()),
                ('moneda_funcional', models.CharField(choices=[('CLP', 'CLP'), ('UF', 'UF')], default='CLP', max_length=8)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('inactiva', 'Inactiva')], default='borrador', max_length=16)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_fiscal', to='patrimonio.empresa')),
                ('regimen_tributario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones_fiscales', to='contabilidad.regimentributarioempresa')),
            ],
            options={
                'ordering': ['empresa_id'],
            },
        ),
        migrations.CreateModel(
            name='ReglaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evento_tipo', models.CharField(max_length=64)),
                ('plan_cuentas_version', models.CharField(max_length=32)),
                ('criterio_cargo', models.TextField(blank=True)),
                ('criterio_abono', models.TextField(blank=True)),
                ('vigencia_desde', models.DateField()),
                ('vigencia_hasta', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=16)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_contables', to='patrimonio.empresa')),
            ],
            options={
                'ordering': ['empresa_id', 'evento_tipo', '-vigencia_desde'],
            },
        ),
        migrations.CreateModel(
            name='MatrizReglasContables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condicion_impuesto', models.CharField(blank=True, max_length=128)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=16)),
                ('cuenta_debe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reglas_debe', to='contabilidad.cuentacontable')),
                ('cuenta_haber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reglas_haber', to='contabilidad.cuentacontable')),
                ('regla_contable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas_matriz', to='contabilidad.reglacontable')),
            ],
            options={
                'ordering': ['regla_contable_id', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='cuentacontable',
            constraint=models.UniqueConstraint(fields=('empresa', 'plan_cuentas_version', 'codigo'), name='uniq_cuenta_contable_por_empresa_version_codigo'),
        ),
    ]
