# Generated by Django 5.2.12 on 2026-03-18 11:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_default_regime'),
        ('patrimonio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionfiscalempresa',
            name='tasa_ppm_vigente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.CreateModel(
            name='PoliticaReversoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_ajuste', models.CharField(max_length=64)),
                ('usa_reverso', models.BooleanField(default=False)),
                ('usa_asiento_complementario', models.BooleanField(default=True)),
                ('permite_reapertura', models.BooleanField(default=False)),
                ('aprobacion_requerida', models.BooleanField(default=True)),
                ('ventana_operativa', models.CharField(blank=True, max_length=64)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=16)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='politicas_reverso_contable', to='patrimonio.empresa')),
            ],
            options={
                'ordering': ['empresa_id', 'tipo_ajuste'],
            },
        ),
        migrations.CreateModel(
            name='BalanceComprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('periodo', models.CharField(max_length=7)),
                ('estado_snapshot', models.CharField(choices=[('borrador', 'Borrador'), ('preparado', 'Preparado'), ('aprobado', 'Aprobado'), ('reabierto', 'Reabierto')], default='preparado', max_length=16)),
                ('storage_ref', models.CharField(blank=True, max_length=255)),
                ('resumen', models.JSONField(blank=True, default=dict)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances_comprobacion', to='patrimonio.empresa')),
            ],
            options={
                'ordering': ['empresa_id', '-periodo'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'periodo'), name='uniq_balance_comprobacion_por_empresa_periodo')],
            },
        ),
        migrations.CreateModel(
            name='CierreMensualContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anio', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('preparado', 'Preparado'), ('aprobado', 'Aprobado'), ('reabierto', 'Reabierto')], default='borrador', max_length=16)),
                ('fecha_preparacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('resumen_obligaciones', models.JSONField(blank=True, default=dict)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cierres_mensuales_contables', to='patrimonio.empresa')),
            ],
            options={
                'ordering': ['empresa_id', '-anio', '-mes'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'anio', 'mes'), name='uniq_cierre_mensual_por_empresa_periodo')],
            },
        ),
        migrations.CreateModel(
            name='LibroDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('periodo', models.CharField(max_length=7)),
                ('estado_snapshot', models.CharField(choices=[('borrador', 'Borrador'), ('preparado', 'Preparado'), ('aprobado', 'Aprobado'), ('reabierto', 'Reabierto')], default='preparado', max_length=16)),
                ('storage_ref', models.CharField(blank=True, max_length=255)),
                ('resumen', models.JSONField(blank=True, default=dict)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros_diario', to='patrimonio.empresa')),
            ],
            options={
                'ordering': ['empresa_id', '-periodo'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'periodo'), name='uniq_libro_diario_por_empresa_periodo')],
            },
        ),
        migrations.CreateModel(
            name='LibroMayor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('periodo', models.CharField(max_length=7)),
                ('estado_snapshot', models.CharField(choices=[('borrador', 'Borrador'), ('preparado', 'Preparado'), ('aprobado', 'Aprobado'), ('reabierto', 'Reabierto')], default='preparado', max_length=16)),
                ('storage_ref', models.CharField(blank=True, max_length=255)),
                ('resumen', models.JSONField(blank=True, default=dict)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros_mayor', to='patrimonio.empresa')),
            ],
            options={
                'ordering': ['empresa_id', '-periodo'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'periodo'), name='uniq_libro_mayor_por_empresa_periodo')],
            },
        ),
        migrations.CreateModel(
            name='ObligacionTributariaMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anio', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('obligacion_tipo', models.CharField(max_length=32)),
                ('base_imponible', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('monto_calculado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('estado_preparacion', models.CharField(choices=[('no_aplica', 'No aplica'), ('pendiente_datos', 'Pendiente datos'), ('en_preparacion', 'En preparacion'), ('preparado', 'Preparado'), ('aprobado_para_presentacion', 'Aprobado para presentacion'), ('presentado', 'Presentado'), ('observado', 'Observado'), ('rectificado', 'Rectificado')], default='pendiente_datos', max_length=32)),
                ('detalle_calculo', models.JSONField(blank=True, default=dict)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligaciones_tributarias_mensuales', to='patrimonio.empresa')),
            ],
            options={
                'ordering': ['empresa_id', '-anio', '-mes', 'obligacion_tipo'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'anio', 'mes', 'obligacion_tipo'), name='uniq_obligacion_tributaria_por_empresa_periodo_tipo')],
            },
        ),
    ]
