# Generated by Django 5.2.12 on 2026-05-26 00:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_configuracionfiscalempresa_tasa_ppm_vigente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EfectoReaperturaCierreMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_efecto', models.CharField(choices=[('reverso', 'Reverso'), ('asiento_complementario', 'Asiento complementario')], max_length=32)),
                ('monto_efecto', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('motivo', models.CharField(max_length=255)),
                ('efecto_esperado', models.CharField(max_length=255)),
                ('evidencia_ref', models.CharField(max_length=255)),
                ('fecha_aplicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efectos_reapertura', to='contabilidad.cierremensualcontable')),
                ('evento_contable', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='efecto_reapertura_cierre', to='contabilidad.eventocontable')),
                ('politica_reverso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='efectos_reapertura', to='contabilidad.politicareversocontable')),
            ],
            options={
                'ordering': ['cierre_id', 'created_at', 'id'],
            },
        ),
    ]
