# Generated by Django 5.2.12 on 2026-05-29 16:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0004_efectoreaperturacierremensual'),
        ('patrimonio', '0006_representacioncomunidad_evidencia_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidacionMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_tipo', models.CharField(choices=[('empresa', 'Empresa'), ('comunidad', 'Comunidad'), ('socio', 'Socio')], max_length=16)),
                ('anio', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('preparada', 'Preparada'), ('aprobada', 'Aprobada'), ('observada', 'Observada')], default='borrador', max_length=16)),
                ('comision_administracion_aplica', models.BooleanField(default=False)),
                ('saldo_final_clp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('saldo_final_explicacion', models.CharField(blank=True, max_length=255)),
                ('saldo_final_evidencia_ref', models.CharField(blank=True, max_length=255)),
                ('evidencia_base_ref', models.CharField(blank=True, max_length=255)),
                ('responsable_ref', models.CharField(blank=True, max_length=255)),
                ('cierre_contable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_mensuales', to='contabilidad.cierremensualcontable')),
                ('comunidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_mensuales', to='patrimonio.comunidadpatrimonial')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_mensuales', to='patrimonio.empresa')),
                ('socio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_mensuales', to='patrimonio.socio')),
            ],
            options={
                'ordering': ['owner_tipo', '-anio', '-mes', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LineaLiquidacionMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_linea', models.CharField(choices=[('ingreso_arriendo', 'Ingreso arriendo'), ('egreso_operativo', 'Egreso operativo'), ('comision_administracion', 'Comision administracion'), ('distribucion_socio', 'Distribucion socio'), ('provision_impuesto', 'Provision impuesto'), ('ajuste', 'Ajuste'), ('saldo_final_explicado', 'Saldo final explicado')], max_length=32)),
                ('descripcion', models.CharField(max_length=255)),
                ('monto_clp', models.DecimalField(decimal_places=2, max_digits=14)),
                ('evidencia_ref', models.CharField(blank=True, max_length=255)),
                ('beneficiario_socio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lineas_liquidacion_beneficiario', to='patrimonio.socio')),
                ('evento_contable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lineas_liquidacion', to='contabilidad.eventocontable')),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='contabilidad.liquidacionmensual')),
            ],
            options={
                'ordering': ['liquidacion_id', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='liquidacionmensual',
            constraint=models.UniqueConstraint(condition=models.Q(('empresa__isnull', False), ('owner_tipo', 'empresa')), fields=('empresa', 'anio', 'mes'), name='uniq_liquidacion_empresa_periodo'),
        ),
        migrations.AddConstraint(
            model_name='liquidacionmensual',
            constraint=models.UniqueConstraint(condition=models.Q(('comunidad__isnull', False), ('owner_tipo', 'comunidad')), fields=('comunidad', 'anio', 'mes'), name='uniq_liquidacion_comunidad_periodo'),
        ),
        migrations.AddConstraint(
            model_name='liquidacionmensual',
            constraint=models.UniqueConstraint(condition=models.Q(('owner_tipo', 'socio'), ('socio__isnull', False)), fields=('socio', 'anio', 'mes'), name='uniq_liquidacion_socio_periodo'),
        ),
    ]
