# Generated by Django 5.2.12 on 2026-03-18 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cobranza', '0003_pagomensual_monto_facturable_clp'),
        ('contratos', '0001_initial'),
        ('patrimonio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacidadTributariaSII',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capacidad_key', models.CharField(choices=[('DTEEmision', 'DTE Emision'), ('DTEConsultaEstado', 'DTE Consulta Estado'), ('F29Preparacion', 'F29 Preparacion'), ('F29Presentacion', 'F29 Presentacion'), ('DDJJPreparacion', 'DDJJ Preparacion'), ('F22Preparacion', 'F22 Preparacion')], max_length=32)),
                ('certificado_ref', models.CharField(blank=True, max_length=255)),
                ('ambiente', models.CharField(choices=[('certificacion', 'Certificacion'), ('produccion', 'Produccion')], default='certificacion', max_length=16)),
                ('estado_gate', models.CharField(choices=[('abierto', 'Abierto'), ('condicionado', 'Condicionado'), ('cerrado', 'Cerrado'), ('suspendido', 'Suspendido'), ('podado', 'Podado')], default='condicionado', max_length=16)),
                ('ultimo_resultado', models.JSONField(blank=True, default=dict)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacidades_sii', to='patrimonio.empresa')),
            ],
            options={
                'ordering': ['empresa_id', 'capacidad_key'],
            },
        ),
        migrations.CreateModel(
            name='DTEEmitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_dte', models.CharField(choices=[('34', 'Factura Exenta'), ('56', 'Nota de Debito'), ('61', 'Nota de Credito')], default='34', max_length=3)),
                ('monto_neto_clp', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha_emision', models.DateField()),
                ('estado_dte', models.CharField(choices=[('borrador', 'Borrador'), ('enviado_manual_controlado', 'Enviado manual controlado'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('anulado', 'Anulado')], default='borrador', max_length=32)),
                ('sii_track_id', models.CharField(blank=True, max_length=64)),
                ('ultimo_estado_sii', models.CharField(blank=True, max_length=128)),
                ('observaciones', models.TextField(blank=True)),
                ('arrendatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dtes_emitidos', to='contratos.arrendatario')),
                ('capacidad_tributaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dtes_emitidos', to='sii.capacidadtributariasii')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dtes_emitidos', to='contratos.contrato')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dtes_emitidos', to='patrimonio.empresa')),
                ('pago_mensual', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dte_emitido', to='cobranza.pagomensual')),
            ],
            options={
                'ordering': ['-fecha_emision', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='capacidadtributariasii',
            constraint=models.UniqueConstraint(fields=('empresa', 'capacidad_key'), name='uniq_capacidad_sii_por_empresa'),
        ),
    ]
