# Generated by Django 5.2.12 on 2026-03-21 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_configuracionfiscalempresa_tasa_ppm_vigente_and_more'),
        ('patrimonio', '0001_initial'),
        ('sii', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='F29PreparacionMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anio', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('estado_preparacion', models.CharField(choices=[('no_aplica', 'No aplica'), ('pendiente_datos', 'Pendiente datos'), ('en_preparacion', 'En preparacion'), ('preparado', 'Preparado'), ('aprobado_para_presentacion', 'Aprobado para presentacion'), ('presentado', 'Presentado'), ('observado', 'Observado'), ('rectificado', 'Rectificado')], default='pendiente_datos', max_length=32)),
                ('resumen_formulario', models.JSONField(blank=True, default=dict)),
                ('borrador_ref', models.CharField(blank=True, max_length=255)),
                ('observaciones', models.TextField(blank=True)),
                ('capacidad_tributaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='f29_preparados', to='sii.capacidadtributariasii')),
                ('cierre_mensual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='f29_preparados', to='contabilidad.cierremensualcontable')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='f29_preparados', to='patrimonio.empresa')),
            ],
            options={
                'ordering': ['empresa_id', '-anio', '-mes'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'anio', 'mes'), name='uniq_f29_preparacion_por_empresa_periodo')],
            },
        ),
    ]
