# Generated by Django 5.2.12 on 2026-03-21 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0001_initial'),
        ('sii', '0002_f29preparacionmensual'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesoRentaAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anio_tributario', models.PositiveSmallIntegerField()),
                ('estado', models.CharField(choices=[('no_aplica', 'No aplica'), ('pendiente_datos', 'Pendiente datos'), ('en_preparacion', 'En preparacion'), ('preparado', 'Preparado'), ('aprobado_para_presentacion', 'Aprobado para presentacion'), ('presentado', 'Presentado'), ('observado', 'Observado'), ('rectificado', 'Rectificado')], default='pendiente_datos', max_length=32)),
                ('fecha_preparacion', models.DateTimeField(blank=True, null=True)),
                ('resumen_anual', models.JSONField(blank=True, default=dict)),
                ('paquete_ddjj_ref', models.CharField(blank=True, max_length=255)),
                ('borrador_f22_ref', models.CharField(blank=True, max_length=255)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procesos_renta_anual', to='patrimonio.empresa')),
            ],
            options={
                'ordering': ['empresa_id', '-anio_tributario'],
            },
        ),
        migrations.CreateModel(
            name='F22PreparacionAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anio_tributario', models.PositiveSmallIntegerField()),
                ('estado_preparacion', models.CharField(choices=[('no_aplica', 'No aplica'), ('pendiente_datos', 'Pendiente datos'), ('en_preparacion', 'En preparacion'), ('preparado', 'Preparado'), ('aprobado_para_presentacion', 'Aprobado para presentacion'), ('presentado', 'Presentado'), ('observado', 'Observado'), ('rectificado', 'Rectificado')], default='pendiente_datos', max_length=32)),
                ('resumen_f22', models.JSONField(blank=True, default=dict)),
                ('borrador_ref', models.CharField(blank=True, max_length=255)),
                ('observaciones', models.TextField(blank=True)),
                ('capacidad_tributaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='f22_preparados', to='sii.capacidadtributariasii')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='f22_preparados', to='patrimonio.empresa')),
                ('proceso_renta_anual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='f22_preparados', to='sii.procesorentaanual')),
            ],
            options={
                'ordering': ['empresa_id', '-anio_tributario'],
            },
        ),
        migrations.CreateModel(
            name='DDJJPreparacionAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anio_tributario', models.PositiveSmallIntegerField()),
                ('estado_preparacion', models.CharField(choices=[('no_aplica', 'No aplica'), ('pendiente_datos', 'Pendiente datos'), ('en_preparacion', 'En preparacion'), ('preparado', 'Preparado'), ('aprobado_para_presentacion', 'Aprobado para presentacion'), ('presentado', 'Presentado'), ('observado', 'Observado'), ('rectificado', 'Rectificado')], default='pendiente_datos', max_length=32)),
                ('resumen_paquete', models.JSONField(blank=True, default=dict)),
                ('paquete_ref', models.CharField(blank=True, max_length=255)),
                ('observaciones', models.TextField(blank=True)),
                ('capacidad_tributaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ddjj_preparadas', to='sii.capacidadtributariasii')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ddjj_preparadas', to='patrimonio.empresa')),
                ('proceso_renta_anual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ddjj_preparadas', to='sii.procesorentaanual')),
            ],
            options={
                'ordering': ['empresa_id', '-anio_tributario'],
            },
        ),
        migrations.AddConstraint(
            model_name='procesorentaanual',
            constraint=models.UniqueConstraint(fields=('empresa', 'anio_tributario'), name='uniq_proceso_renta_anual_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='f22preparacionanual',
            constraint=models.UniqueConstraint(fields=('empresa', 'anio_tributario'), name='uniq_f22_preparacion_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='ddjjpreparacionanual',
            constraint=models.UniqueConstraint(fields=('empresa', 'anio_tributario'), name='uniq_ddjj_preparacion_por_empresa'),
        ),
    ]
