# Generated by Django 5.2.12 on 2026-05-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sii', '0004_dte_emitido_distribucion_cobro_mensual'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacidadtributariasii',
            name='autorizacion_ambiente_ref',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='capacidadtributariasii',
            name='evidencia_ref',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='capacidadtributariasii',
            name='prueba_flujo_ref',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='capacidadtributariasii',
            name='regla_fiscal_ref',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
