# Generated by Codex on 2026-06-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sii', '0005_capacidad_sii_readiness_refs'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesorentaanual',
            name='responsable_revision_ref',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ddjjpreparacionanual',
            name='responsable_revision_ref',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='f22preparacionanual',
            name='responsable_revision_ref',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
