# Generated by Django 5.2.12 on 2026-06-14 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sii', '0006_annual_review_responsible_refs'),
    ]

    operations = [
        migrations.AddField(
            model_name='f29preparacionmensual',
            name='responsable_revision_ref',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
