# Generated by Django 5.2.12 on 2026-06-14 04:11

import django.db.models.deletion
import sii.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_liquidacionmensual_linealiquidacionmensual_and_more'),
        ('sii', '0007_f29preparacionmensual_responsable_revision_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxYearRuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anio_tributario', models.PositiveSmallIntegerField()),
                ('version', models.CharField(max_length=32)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('aprobada', 'Aprobada'), ('condicionada', 'Condicionada'), ('retirada', 'Retirada')], default='borrador', max_length=16)),
                ('fuente_ref', models.CharField(blank=True, max_length=255)),
                ('hash_normativo', models.CharField(blank=True, max_length=64)),
                ('responsable_aprobacion_ref', models.CharField(blank=True, max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('regimen_tributario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_year_rule_sets', to='contabilidad.regimentributarioempresa')),
            ],
            options={
                'ordering': ['-anio_tributario', 'regimen_tributario_id', 'version'],
            },
            bases=(sii.models.OperationalSIITextNormalizationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TaxCodeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destino', models.CharField(choices=[('RLI', 'RLI'), ('CPT', 'CPT'), ('RAI', 'RAI'), ('SAC', 'SAC'), ('DDJJ', 'DDJJ'), ('F22', 'F22'), ('DOSSIER', 'Dossier')], max_length=16)),
                ('codigo_interno', models.CharField(max_length=64)),
                ('codigo_destino', models.CharField(max_length=64)),
                ('formula_ref', models.CharField(blank=True, max_length=255)),
                ('evidencia_ref', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_mappings', to='sii.taxyearruleset')),
            ],
            options={
                'ordering': ['rule_set_id', 'destino', 'codigo_interno', 'codigo_destino'],
            },
            bases=(sii.models.OperationalSIITextNormalizationMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='taxyearruleset',
            constraint=models.UniqueConstraint(fields=('anio_tributario', 'regimen_tributario', 'version'), name='uniq_tax_year_ruleset_version'),
        ),
        migrations.AddConstraint(
            model_name='taxyearruleset',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'aprobada')), fields=('anio_tributario', 'regimen_tributario'), name='uniq_tax_year_ruleset_approved'),
        ),
        migrations.AddConstraint(
            model_name='taxcodemapping',
            constraint=models.UniqueConstraint(fields=('rule_set', 'destino', 'codigo_interno', 'codigo_destino'), name='uniq_tax_code_mapping_target'),
        ),
    ]
