# Generated by Django 5.2.12 on 2026-06-14 04:53

import django.db.models.deletion
import sii.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0006_representacioncomunidad_evidencia_ref'),
        ('sii', '0008_taxyearruleset_taxcodemapping_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualTaxSourceBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anio_tributario', models.PositiveSmallIntegerField()),
                ('anio_comercial', models.PositiveSmallIntegerField()),
                ('source_kind', models.CharField(choices=[('local', 'Local'), ('fixture', 'Fixture'), ('demo', 'Demo'), ('snapshot_controlado', 'Snapshot controlado'), ('real_autorizado', 'Real autorizado')], default='local', max_length=32)),
                ('source_label', models.CharField(blank=True, max_length=255)),
                ('authorization_ref', models.CharField(blank=True, max_length=255)),
                ('responsible_ref', models.CharField(blank=True, max_length=255)),
                ('hash_fuentes', models.CharField(blank=True, max_length=64)),
                ('resumen_fuentes', models.JSONField(blank=True, default=dict)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('congelado', 'Congelado'), ('retirado', 'Retirado')], default='borrador', max_length=16)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annual_tax_source_bundles', to='patrimonio.empresa')),
            ],
            options={
                'ordering': ['empresa_id', '-anio_tributario', 'source_kind', 'source_label'],
            },
            bases=(sii.models.OperationalSIITextNormalizationMixin, models.Model),
        ),
        migrations.AddField(
            model_name='procesorentaanual',
            name='source_bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procesos_renta_anual', to='sii.annualtaxsourcebundle'),
        ),
        migrations.AddConstraint(
            model_name='annualtaxsourcebundle',
            constraint=models.UniqueConstraint(fields=('empresa', 'anio_tributario', 'source_kind', 'source_label'), name='uniq_annual_tax_source_bundle_label'),
        ),
        migrations.AddConstraint(
            model_name='annualtaxsourcebundle',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'congelado')), fields=('empresa', 'anio_tributario'), name='uniq_annual_tax_source_bundle_frozen'),
        ),
    ]
