# Generated by Django 5.2.12 on 2026-06-14 05:39

import django.db.models.deletion
import sii.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_liquidacionmensual_linealiquidacionmensual_and_more'),
        ('patrimonio', '0006_representacioncomunidad_evidencia_ref'),
        ('sii', '0009_annualtaxsourcebundle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyTaxFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anio', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('source_ref', models.CharField(blank=True, max_length=255)),
                ('responsible_ref', models.CharField(blank=True, max_length=255)),
                ('resumen_hecho', models.JSONField(blank=True, default=dict)),
                ('hash_hecho', models.CharField(blank=True, max_length=64)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('normalizado', 'Normalizado'), ('retirado', 'Retirado')], default='borrador', max_length=16)),
                ('cierre_mensual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_tax_facts', to='contabilidad.cierremensualcontable')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_tax_facts', to='patrimonio.empresa')),
                ('f29_preparacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_tax_facts', to='sii.f29preparacionmensual')),
                ('liquidacion_mensual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_tax_facts', to='contabilidad.liquidacionmensual')),
            ],
            options={
                'ordering': ['empresa_id', '-anio', 'mes'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'anio', 'mes'), name='uniq_monthly_tax_fact_por_empresa_periodo')],
            },
            bases=(sii.models.OperationalSIITextNormalizationMixin, models.Model),
        ),
    ]
