# Generated by Django 5.2.12 on 2026-06-14 06:22

import django.db.models.deletion
import sii.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0006_representacioncomunidad_evidencia_ref'),
        ('sii', '0010_monthlytaxfact'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualTaxWorkbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anio_tributario', models.PositiveSmallIntegerField()),
                ('anio_comercial', models.PositiveSmallIntegerField()),
                ('tipo', models.CharField(choices=[('RLI', 'RLI'), ('CPT', 'CPT')], max_length=8)),
                ('source_ref', models.CharField(blank=True, max_length=255)),
                ('responsible_ref', models.CharField(blank=True, max_length=255)),
                ('resumen_workbook', models.JSONField(blank=True, default=dict)),
                ('hash_workbook', models.CharField(blank=True, max_length=64)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('preparado', 'Preparado'), ('retirado', 'Retirado')], default='borrador', max_length=16)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annual_tax_workbooks', to='patrimonio.empresa')),
                ('proceso_renta_anual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_workbooks', to='sii.procesorentaanual')),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_workbooks', to='sii.taxyearruleset')),
                ('source_bundle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_workbooks', to='sii.annualtaxsourcebundle')),
            ],
            options={
                'ordering': ['empresa_id', '-anio_tributario', 'tipo'],
            },
            bases=(sii.models.OperationalSIITextNormalizationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AnnualTaxWorkbookLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo_interno', models.CharField(max_length=64)),
                ('codigo_destino', models.CharField(max_length=64)),
                ('origen', models.CharField(max_length=64)),
                ('signo', models.CharField(choices=[('suma', 'Suma'), ('resta', 'Resta'), ('informativo', 'Informativo')], default='informativo', max_length=16)),
                ('monto_clp', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('formula_ref', models.CharField(blank=True, max_length=255)),
                ('evidencia_ref', models.CharField(blank=True, max_length=255)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('hash_linea', models.CharField(blank=True, max_length=64)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=16)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annual_tax_lines', to='sii.taxcodemapping')),
                ('workbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sii.annualtaxworkbook')),
            ],
            options={
                'ordering': ['workbook_id', 'codigo_interno', 'codigo_destino'],
            },
            bases=(sii.models.OperationalSIITextNormalizationMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='annualtaxworkbook',
            constraint=models.UniqueConstraint(fields=('proceso_renta_anual', 'tipo'), name='uniq_annual_tax_workbook_process_tipo'),
        ),
        migrations.AddConstraint(
            model_name='annualtaxworkbookline',
            constraint=models.UniqueConstraint(fields=('workbook', 'codigo_interno', 'codigo_destino'), name='uniq_annual_tax_workbook_line_target'),
        ),
    ]
