# Generated by Django 5.2.12 on 2026-06-14 07:17

import django.db.models.deletion
import sii.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0006_representacioncomunidad_evidencia_ref'),
        ('sii', '0011_annualtaxworkbook_annualtaxworkbookline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualEnterpriseRegisterSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anio_tributario', models.PositiveSmallIntegerField()),
                ('anio_comercial', models.PositiveSmallIntegerField()),
                ('tipo_registro', models.CharField(choices=[('RAI', 'RAI'), ('SAC', 'SAC'), ('RETIROS', 'Retiros'), ('DIVIDENDOS', 'Dividendos')], max_length=16)),
                ('source_ref', models.CharField(blank=True, max_length=255)),
                ('responsible_ref', models.CharField(blank=True, max_length=255)),
                ('saldo_inicial_clp', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('movimientos_total_clp', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('saldo_final_clp', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('resumen_registro', models.JSONField(blank=True, default=dict)),
                ('hash_registro', models.CharField(blank=True, max_length=64)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('preparado', 'Preparado'), ('retirado', 'Retirado')], default='borrador', max_length=16)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annual_enterprise_registers', to='patrimonio.empresa')),
                ('proceso_renta_anual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enterprise_registers', to='sii.procesorentaanual')),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enterprise_registers', to='sii.taxyearruleset')),
                ('source_bundle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enterprise_registers', to='sii.annualtaxsourcebundle')),
            ],
            options={
                'ordering': ['empresa_id', '-anio_tributario', 'tipo_registro'],
            },
            bases=(sii.models.OperationalSIITextNormalizationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AnnualEnterpriseRegisterMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo_interno', models.CharField(max_length=64)),
                ('origen', models.CharField(max_length=64)),
                ('signo', models.CharField(choices=[('suma', 'Suma'), ('resta', 'Resta'), ('informativo', 'Informativo')], default='informativo', max_length=16)),
                ('monto_clp', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('formula_ref', models.CharField(blank=True, max_length=255)),
                ('evidencia_ref', models.CharField(blank=True, max_length=255)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('hash_movimiento', models.CharField(blank=True, max_length=64)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=16)),
                ('source_workbook_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enterprise_register_movements', to='sii.annualtaxworkbookline')),
                ('register_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='sii.annualenterpriseregisterset')),
            ],
            options={
                'ordering': ['register_set_id', 'codigo_interno', 'origen'],
            },
            bases=(sii.models.OperationalSIITextNormalizationMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='annualenterpriseregisterset',
            constraint=models.UniqueConstraint(fields=('proceso_renta_anual', 'tipo_registro'), name='uniq_annual_enterprise_register_process_tipo'),
        ),
        migrations.AddConstraint(
            model_name='annualenterpriseregistermovement',
            constraint=models.UniqueConstraint(fields=('register_set', 'codigo_interno', 'origen'), name='uniq_enterprise_register_movement_origin'),
        ),
    ]
