# Generated by Django 5.2.12 on 2026-06-14 08:00

import django.db.models.deletion
import sii.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0006_representacioncomunidad_evidencia_ref'),
        ('sii', '0012_annualenterpriseregisterset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualRealEstateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anio_tributario', models.PositiveSmallIntegerField()),
                ('anio_comercial', models.PositiveSmallIntegerField()),
                ('source_ref', models.CharField(blank=True, max_length=255)),
                ('responsible_ref', models.CharField(blank=True, max_length=255)),
                ('propiedades_total', models.PositiveIntegerField(default=0)),
                ('arriendo_devengado_total_clp', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('arriendo_conciliado_total_clp', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('arriendo_facturable_total_clp', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('contribuciones_total_clp', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('resumen_seccion', models.JSONField(blank=True, default=dict)),
                ('hash_seccion', models.CharField(blank=True, max_length=64)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('preparado', 'Preparado'), ('retirado', 'Retirado')], default='borrador', max_length=16)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annual_real_estate_sections', to='patrimonio.empresa')),
                ('proceso_renta_anual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='real_estate_sections', to='sii.procesorentaanual')),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='real_estate_sections', to='sii.taxyearruleset')),
                ('source_bundle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='real_estate_sections', to='sii.annualtaxsourcebundle')),
            ],
            options={
                'ordering': ['empresa_id', '-anio_tributario', 'id'],
            },
            bases=(sii.models.OperationalSIITextNormalizationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AnnualRealEstateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo_propiedad_snapshot', models.CharField(max_length=16)),
                ('rol_avaluo_snapshot', models.CharField(blank=True, max_length=64)),
                ('direccion_snapshot', models.CharField(max_length=255)),
                ('comuna_snapshot', models.CharField(max_length=100)),
                ('region_snapshot', models.CharField(max_length=100)),
                ('tipo_inmueble_snapshot', models.CharField(max_length=32)),
                ('owner_tipo_snapshot', models.CharField(max_length=32)),
                ('owner_id_snapshot', models.PositiveIntegerField()),
                ('arriendo_devengado_clp', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('arriendo_conciliado_clp', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('arriendo_facturable_clp', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('contribuciones_clp', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('formula_ref', models.CharField(blank=True, max_length=255)),
                ('evidencia_ref', models.CharField(blank=True, max_length=255)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('hash_item', models.CharField(blank=True, max_length=64)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=16)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annual_real_estate_items', to='patrimonio.propiedad')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sii.annualrealestatesection')),
            ],
            options={
                'ordering': ['section_id', 'codigo_propiedad_snapshot', 'propiedad_id'],
            },
            bases=(sii.models.OperationalSIITextNormalizationMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='annualrealestatesection',
            constraint=models.UniqueConstraint(fields=('proceso_renta_anual',), name='uniq_annual_real_estate_section_process'),
        ),
        migrations.AddConstraint(
            model_name='annualrealestateitem',
            constraint=models.UniqueConstraint(fields=('section', 'propiedad'), name='uniq_annual_real_estate_item_property'),
        ),
    ]
