# Generated by Django 5.2.12 on 2026-06-14 08:47

import django.db.models.deletion
import sii.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0006_representacioncomunidad_evidencia_ref'),
        ('sii', '0013_annualrealestatesection_annualrealestateitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualTaxArtifactMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anio_tributario', models.PositiveSmallIntegerField()),
                ('anio_comercial', models.PositiveSmallIntegerField()),
                ('source_ref', models.CharField(blank=True, max_length=255)),
                ('responsible_ref', models.CharField(blank=True, max_length=255)),
                ('items_total', models.PositiveIntegerField(default=0)),
                ('ddjj_items_total', models.PositiveIntegerField(default=0)),
                ('f22_items_total', models.PositiveIntegerField(default=0)),
                ('resumen_matriz', models.JSONField(blank=True, default=dict)),
                ('hash_matriz', models.CharField(blank=True, max_length=64)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('preparado', 'Preparado'), ('retirado', 'Retirado')], default='borrador', max_length=16)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annual_tax_artifact_matrices', to='patrimonio.empresa')),
                ('proceso_renta_anual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifact_matrices', to='sii.procesorentaanual')),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifact_matrices', to='sii.taxyearruleset')),
                ('source_bundle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifact_matrices', to='sii.annualtaxsourcebundle')),
            ],
            options={
                'ordering': ['empresa_id', '-anio_tributario', 'id'],
            },
            bases=(sii.models.OperationalSIITextNormalizationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AnnualTaxArtifactMatrixItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_kind', models.CharField(choices=[('DDJJ', 'DDJJ'), ('F22', 'F22')], max_length=8)),
                ('target_code', models.CharField(max_length=64)),
                ('medio_sii', models.CharField(max_length=64)),
                ('source_kind', models.CharField(choices=[('source_bundle', 'Source bundle'), ('tax_mapping', 'Tax code mapping'), ('annual_summary', 'Annual summary'), ('annual_workbook', 'Annual workbook'), ('enterprise_register', 'Enterprise register'), ('real_estate', 'Real estate'), ('fiscal_config', 'Fiscal config')], max_length=32)),
                ('source_model', models.CharField(max_length=64)),
                ('source_object_id', models.PositiveIntegerField()),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('review_state', models.CharField(choices=[('listo_revision', 'Listo para revision'), ('requiere_revision', 'Requiere revision'), ('bloqueado', 'Bloqueado')], default='listo_revision', max_length=24)),
                ('formula_ref', models.CharField(blank=True, max_length=255)),
                ('evidencia_ref', models.CharField(blank=True, max_length=255)),
                ('responsible_ref', models.CharField(blank=True, max_length=255)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('hash_item', models.CharField(blank=True, max_length=64)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=16)),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sii.annualtaxartifactmatrix')),
            ],
            options={
                'ordering': ['matrix_id', 'target_kind', 'target_code', 'source_kind', 'source_model', 'source_object_id'],
            },
            bases=(sii.models.OperationalSIITextNormalizationMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='annualtaxartifactmatrix',
            constraint=models.UniqueConstraint(fields=('proceso_renta_anual',), name='uniq_annual_tax_artifact_matrix_process'),
        ),
        migrations.AddConstraint(
            model_name='annualtaxartifactmatrixitem',
            constraint=models.UniqueConstraint(fields=('matrix', 'target_kind', 'target_code', 'source_kind', 'source_model', 'source_object_id'), name='uniq_annual_tax_artifact_matrix_item_source'),
        ),
    ]
