# Generated by Django 5.2.12 on 2026-06-14 09:29

import django.db.models.deletion
import sii.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0006_representacioncomunidad_evidencia_ref'),
        ('sii', '0014_annualtaxartifactmatrix_annualtaxartifactmatrixitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualTaxDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anio_tributario', models.PositiveSmallIntegerField()),
                ('anio_comercial', models.PositiveSmallIntegerField()),
                ('source_ref', models.CharField(blank=True, max_length=255)),
                ('responsible_ref', models.CharField(blank=True, max_length=255)),
                ('dossier_ref', models.CharField(blank=True, max_length=255)),
                ('review_state', models.CharField(choices=[('listo_revision', 'Listo para revision'), ('requiere_revision', 'Requiere revision'), ('bloqueado', 'Bloqueado')], default='listo_revision', max_length=24)),
                ('monthly_facts_total', models.PositiveIntegerField(default=0)),
                ('workbooks_total', models.PositiveIntegerField(default=0)),
                ('enterprise_registers_total', models.PositiveIntegerField(default=0)),
                ('real_estate_sections_total', models.PositiveIntegerField(default=0)),
                ('artifact_matrix_items_total', models.PositiveIntegerField(default=0)),
                ('warnings_total', models.PositiveIntegerField(default=0)),
                ('resumen_dossier', models.JSONField(blank=True, default=dict)),
                ('hash_dossier', models.CharField(blank=True, max_length=64)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('preparado', 'Preparado'), ('retirado', 'Retirado')], default='borrador', max_length=16)),
                ('artifact_matrix', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_dossiers', to='sii.annualtaxartifactmatrix')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annual_tax_dossiers', to='patrimonio.empresa')),
                ('proceso_renta_anual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_dossiers', to='sii.procesorentaanual')),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_dossiers', to='sii.taxyearruleset')),
                ('source_bundle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_dossiers', to='sii.annualtaxsourcebundle')),
            ],
            options={
                'ordering': ['empresa_id', '-anio_tributario', 'id'],
                'constraints': [models.UniqueConstraint(fields=('proceso_renta_anual',), name='uniq_annual_tax_dossier_process')],
            },
            bases=(sii.models.OperationalSIITextNormalizationMixin, models.Model),
        ),
    ]
