# Generated by Django 5.2.12 on 2026-06-14 10:12

import django.db.models.deletion
import sii.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0006_representacioncomunidad_evidencia_ref'),
        ('sii', '0015_annualtaxdossier'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualTaxExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anio_tributario', models.PositiveSmallIntegerField()),
                ('anio_comercial', models.PositiveSmallIntegerField()),
                ('export_kind', models.CharField(choices=[('preview_package', 'Preview package')], default='preview_package', max_length=32)),
                ('source_ref', models.CharField(blank=True, max_length=255)),
                ('responsible_ref', models.CharField(blank=True, max_length=255)),
                ('export_ref', models.CharField(blank=True, max_length=255)),
                ('review_state', models.CharField(choices=[('listo_revision', 'Listo para revision'), ('requiere_revision', 'Requiere revision'), ('bloqueado', 'Bloqueado')], default='listo_revision', max_length=24)),
                ('target_items_total', models.PositiveIntegerField(default=0)),
                ('ddjj_items_total', models.PositiveIntegerField(default=0)),
                ('f22_items_total', models.PositiveIntegerField(default=0)),
                ('warnings_total', models.PositiveIntegerField(default=0)),
                ('official_format', models.BooleanField(default=False)),
                ('sii_submission', models.BooleanField(default=False)),
                ('final_tax_calculation', models.BooleanField(default=False)),
                ('export_payload', models.JSONField(blank=True, default=dict)),
                ('hash_export', models.CharField(blank=True, max_length=64)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('preparado', 'Preparado'), ('retirado', 'Retirado')], default='borrador', max_length=16)),
                ('artifact_matrix', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_exports', to='sii.annualtaxartifactmatrix')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_exports', to='sii.annualtaxdossier')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annual_tax_exports', to='patrimonio.empresa')),
                ('proceso_renta_anual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_exports', to='sii.procesorentaanual')),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_exports', to='sii.taxyearruleset')),
                ('source_bundle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_exports', to='sii.annualtaxsourcebundle')),
            ],
            options={
                'ordering': ['empresa_id', '-anio_tributario', 'export_kind', 'id'],
                'constraints': [models.UniqueConstraint(fields=('proceso_renta_anual', 'export_kind'), name='uniq_annual_tax_export_process_kind')],
            },
            bases=(sii.models.OperationalSIITextNormalizationMixin, models.Model),
        ),
    ]
