# Generated by Django 5.2.12 on 2026-06-14 11:55

import sii.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sii', '0016_annualtaxexport'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualTaxOfficialSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anio_tributario', models.PositiveSmallIntegerField()),
                ('source_key', models.CharField(max_length=96)),
                ('source_type', models.CharField(choices=[('sii_f22_certification', 'SII certificacion F22'), ('sii_f22_instructions', 'SII instrucciones F22'), ('sii_ddjj_media', 'SII medios DDJJ'), ('sii_ddjj_forms', 'SII formularios DDJJ'), ('sii_ddjj_software_houses', 'SII casas software DDJJ'), ('sii_dj1847_instructions', 'SII instrucciones DJ1847'), ('sii_f29_certification', 'SII certificacion F29'), ('sii_dte_technical', 'SII tecnico DTE'), ('expert_review', 'Revision experta')], max_length=64)),
                ('title', models.CharField(max_length=160)),
                ('source_url', models.CharField(blank=True, max_length=255)),
                ('source_ref', models.CharField(blank=True, max_length=255)),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('retrieved_on', models.DateField(blank=True, null=True)),
                ('responsible_ref', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('revisada', 'Revisada'), ('aprobada', 'Aprobada'), ('retirada', 'Retirada')], default='borrador', max_length=16)),
                ('applies_to', models.CharField(blank=True, choices=[('RLI', 'RLI'), ('CPT', 'CPT'), ('RAI', 'RAI'), ('SAC', 'SAC'), ('DDJJ', 'DDJJ'), ('F22', 'F22'), ('DOSSIER', 'Dossier')], max_length=16)),
                ('form_code', models.CharField(blank=True, max_length=32)),
                ('regime_code', models.CharField(blank=True, max_length=64)),
                ('scope_note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-anio_tributario', 'source_type', 'source_key'],
                'constraints': [models.UniqueConstraint(fields=('anio_tributario', 'source_key'), name='uniq_annual_tax_official_source_key')],
            },
            bases=(sii.models.OperationalSIITextNormalizationMixin, models.Model),
        ),
    ]
