# Generated by Django 5.2.12 on 2026-06-14 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sii', '0017_annual_tax_official_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxcodemapping',
            name='official_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='code_mappings', to='sii.annualtaxofficialsource'),
        ),
        migrations.AddField(
            model_name='taxyearruleset',
            name='official_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rule_sets', to='sii.annualtaxofficialsource'),
        ),
    ]
