# Generated by Django 5.2.12 on 2026-06-14 15:50

import django.db.models.deletion
import sii.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0006_representacioncomunidad_evidencia_ref'),
        ('sii', '0018_taxcodemapping_official_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualTaxReviewChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anio_tributario', models.PositiveSmallIntegerField()),
                ('anio_comercial', models.PositiveSmallIntegerField()),
                ('checklist_ref', models.CharField(blank=True, max_length=255)),
                ('responsible_ref', models.CharField(blank=True, max_length=255)),
                ('evidence_ref', models.CharField(blank=True, max_length=255)),
                ('items_total', models.PositiveIntegerField(default=0)),
                ('completed_items_total', models.PositiveIntegerField(default=0)),
                ('blockers_total', models.PositiveIntegerField(default=0)),
                ('warnings_total', models.PositiveIntegerField(default=0)),
                ('review_payload', models.JSONField(blank=True, default=dict)),
                ('hash_checklist', models.CharField(blank=True, max_length=64)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('preparado', 'Preparado'), ('retirado', 'Retirado')], default='borrador', max_length=16)),
                ('annual_export', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_checklists', to='sii.annualtaxexport')),
                ('artifact_matrix', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_review_checklists', to='sii.annualtaxartifactmatrix')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_checklists', to='sii.annualtaxdossier')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annual_tax_review_checklists', to='patrimonio.empresa')),
                ('proceso_renta_anual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_review_checklists', to='sii.procesorentaanual')),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_review_checklists', to='sii.taxyearruleset')),
                ('source_bundle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_review_checklists', to='sii.annualtaxsourcebundle')),
            ],
            options={
                'ordering': ['empresa_id', '-anio_tributario', 'id'],
                'constraints': [models.UniqueConstraint(fields=('proceso_renta_anual',), name='uniq_annual_tax_review_checklist_process')],
            },
            bases=(sii.models.OperationalSIITextNormalizationMixin, models.Model),
        ),
    ]
