# Generated by Django 5.2.12 on 2026-06-14 17:08

import django.db.models.deletion
import sii.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_liquidacionmensual_linealiquidacionmensual_and_more'),
        ('patrimonio', '0006_representacioncomunidad_evidencia_ref'),
        ('sii', '0019_annualtaxreviewchecklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualTaxTrialBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anio_tributario', models.PositiveSmallIntegerField()),
                ('anio_comercial', models.PositiveSmallIntegerField()),
                ('periodo_cierre', models.CharField(max_length=7)),
                ('source_ref', models.CharField(blank=True, max_length=255)),
                ('responsible_ref', models.CharField(blank=True, max_length=255)),
                ('lines_total', models.PositiveIntegerField(default=0)),
                ('warnings_total', models.PositiveIntegerField(default=0)),
                ('resumen_balance', models.JSONField(blank=True, default=dict)),
                ('hash_balance', models.CharField(blank=True, max_length=64)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('preparado', 'Preparado'), ('retirado', 'Retirado')], default='borrador', max_length=16)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annual_tax_trial_balances', to='patrimonio.empresa')),
                ('official_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trial_balances', to='sii.annualtaxofficialsource')),
                ('proceso_renta_anual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trial_balances', to='sii.procesorentaanual')),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trial_balances', to='sii.taxyearruleset')),
                ('source_balance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annual_tax_trial_balances', to='contabilidad.balancecomprobacion')),
                ('source_bundle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trial_balances', to='sii.annualtaxsourcebundle')),
            ],
            options={
                'ordering': ['empresa_id', '-anio_tributario', 'periodo_cierre'],
            },
            bases=(sii.models.OperationalSIITextNormalizationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AnnualTaxTrialBalanceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo_cuenta', models.CharField(max_length=64)),
                ('nombre_cuenta', models.CharField(max_length=255)),
                ('clasificador_dj1847', models.CharField(max_length=64)),
                ('sumas_debe_clp', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('sumas_haber_clp', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('saldo_deudor_clp', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('saldo_acreedor_clp', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('inventario_activo_clp', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('inventario_pasivo_clp', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('resultado_perdida_clp', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('resultado_ganancia_clp', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('formula_ref', models.CharField(blank=True, max_length=255)),
                ('evidencia_ref', models.CharField(blank=True, max_length=255)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('hash_linea', models.CharField(blank=True, max_length=64)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=16)),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annual_tax_trial_balance_lines', to='contabilidad.cuentacontable')),
                ('trial_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sii.annualtaxtrialbalance')),
            ],
            options={
                'ordering': ['trial_balance_id', 'codigo_cuenta'],
            },
            bases=(sii.models.OperationalSIITextNormalizationMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='annualtaxtrialbalance',
            constraint=models.UniqueConstraint(fields=('proceso_renta_anual',), name='uniq_annual_tax_trial_balance_process'),
        ),
        migrations.AddConstraint(
            model_name='annualtaxtrialbalanceline',
            constraint=models.UniqueConstraint(fields=('trial_balance', 'codigo_cuenta'), name='uniq_annual_tax_trial_balance_line_account'),
        ),
    ]
