# Generated by Django 5.2.12 on 2026-06-14 17:52

import django.db.models.deletion
import sii.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sii', '0020_annual_tax_trial_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualtaxartifactmatrixitem',
            name='source_kind',
            field=models.CharField(choices=[('source_bundle', 'Source bundle'), ('tax_mapping', 'Tax code mapping'), ('ddjj_layout', 'DDJJ layout'), ('annual_summary', 'Annual summary'), ('annual_workbook', 'Annual workbook'), ('enterprise_register', 'Enterprise register'), ('real_estate', 'Real estate'), ('fiscal_config', 'Fiscal config')], max_length=32),
        ),
        migrations.CreateModel(
            name='AnnualTaxDDJJFormLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anio_tributario', models.PositiveSmallIntegerField()),
                ('form_code', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=180)),
                ('periodicidad', models.CharField(default='Anual', max_length=32)),
                ('allows_electronic_form', models.BooleanField(default=False)),
                ('allows_file_importer', models.BooleanField(default=False)),
                ('allows_file_upload', models.BooleanField(default=False)),
                ('allows_commercial_software', models.BooleanField(default=False)),
                ('allows_assistant', models.BooleanField(default=False)),
                ('medio_preferente', models.CharField(choices=[('formulario_electronico', 'Formulario electronico'), ('transferencia_archivos_importador', 'Transferencia importador'), ('transferencia_archivos_upload', 'Transferencia upload'), ('software_comercial', 'Software comercial'), ('asistente', 'Asistente')], max_length=64)),
                ('due_date_label', models.CharField(blank=True, max_length=64)),
                ('certificate_code', models.CharField(blank=True, max_length=64)),
                ('certificate_due_label', models.CharField(blank=True, max_length=64)),
                ('resolution_ref', models.CharField(blank=True, max_length=255)),
                ('declaration_status', models.CharField(blank=True, max_length=64)),
                ('layout_ref', models.CharField(blank=True, max_length=255)),
                ('instructions_ref', models.CharField(blank=True, max_length=255)),
                ('responsible_ref', models.CharField(blank=True, max_length=255)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('hash_layout', models.CharField(blank=True, max_length=64)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('preparado', 'Preparado'), ('retirado', 'Retirado')], default='borrador', max_length=16)),
                ('official_form_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ddjj_form_layouts', to='sii.annualtaxofficialsource')),
                ('official_media_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ddjj_media_layouts', to='sii.annualtaxofficialsource')),
                ('official_software_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ddjj_software_layouts', to='sii.annualtaxofficialsource')),
            ],
            options={
                'ordering': ['-anio_tributario', 'form_code'],
                'constraints': [models.UniqueConstraint(fields=('anio_tributario', 'form_code'), name='uniq_annual_tax_ddjj_layout_form')],
            },
            bases=(sii.models.OperationalSIITextNormalizationMixin, models.Model),
        ),
    ]
