# Generated by Django 5.2.12 on 2026-06-14 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sii', '0021_alter_annualtaxartifactmatrixitem_source_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualrealestatesection',
            name='official_contribution_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='real_estate_contribution_sections', to='sii.annualtaxofficialsource'),
        ),
        migrations.AlterField(
            model_name='annualtaxofficialsource',
            name='source_type',
            field=models.CharField(choices=[('sii_f22_certification', 'SII certificacion F22'), ('sii_f22_instructions', 'SII instrucciones F22'), ('sii_ddjj_media', 'SII medios DDJJ'), ('sii_ddjj_forms', 'SII formularios DDJJ'), ('sii_ddjj_software_houses', 'SII casas software DDJJ'), ('sii_dj1847_instructions', 'SII instrucciones DJ1847'), ('sii_real_estate_contributions', 'SII contribuciones bienes raices'), ('sii_f29_certification', 'SII certificacion F29'), ('sii_dte_technical', 'SII tecnico DTE'), ('expert_review', 'Revision experta')], max_length=64),
        ),
    ]
