# Generated by Codex on 2026-06-14

import django.db.models.deletion
import sii.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sii', '0022_annualrealestatesection_official_contribution_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualTaxF22ExportLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anio_tributario', models.PositiveSmallIntegerField()),
                ('form_code', models.CharField(default='F22', max_length=16)),
                ('title', models.CharField(max_length=180)),
                ('allows_local_preview', models.BooleanField(default=True)),
                ('allows_certified_file', models.BooleanField(default=False)),
                ('allows_supervised_portal', models.BooleanField(default=False)),
                ('medio_preferente', models.CharField(choices=[('preview_local_controlado', 'Preview local controlado'), ('archivo_certificado_sii', 'Archivo certificado SII'), ('portal_sii_supervisado', 'Portal SII supervisado')], max_length=64)),
                ('certification_ref', models.CharField(blank=True, max_length=255)),
                ('format_ref', models.CharField(blank=True, max_length=255)),
                ('instructions_ref', models.CharField(blank=True, max_length=255)),
                ('responsible_ref', models.CharField(blank=True, max_length=255)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('hash_layout', models.CharField(blank=True, max_length=64)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('preparado', 'Preparado'), ('retirado', 'Retirado')], default='borrador', max_length=16)),
                ('official_certification_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='f22_export_certification_layouts', to='sii.annualtaxofficialsource')),
                ('official_instructions_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='f22_export_instruction_layouts', to='sii.annualtaxofficialsource')),
            ],
            options={
                'ordering': ['-anio_tributario', 'form_code'],
                'constraints': [models.UniqueConstraint(fields=('anio_tributario', 'form_code'), name='uniq_annual_tax_f22_export_layout_form')],
            },
            bases=(sii.models.OperationalSIITextNormalizationMixin, models.Model),
        ),
        migrations.AddField(
            model_name='annualtaxexport',
            name='official_format_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='annual_tax_exports', to='sii.annualtaxofficialsource'),
        ),
        migrations.AlterField(
            model_name='annualtaxartifactmatrixitem',
            name='source_kind',
            field=models.CharField(choices=[('source_bundle', 'Source bundle'), ('tax_mapping', 'Tax code mapping'), ('ddjj_layout', 'DDJJ layout'), ('f22_export_layout', 'F22 export layout'), ('annual_summary', 'Annual summary'), ('annual_workbook', 'Annual workbook'), ('enterprise_register', 'Enterprise register'), ('real_estate', 'Real estate'), ('fiscal_config', 'Fiscal config')], max_length=32),
        ),
    ]
