# Generated by Codex on 2026-06-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sii', '0023_annualtaxf22exportlayout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualtaxartifactmatrixitem',
            name='warning_review_ref',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
