# Generated by Django 5.2.12 on 2026-06-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sii', '0025_annualtaxworkbookline_warning_review_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualenterpriseregistermovement',
            name='warning_review_ref',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
