# Generated by Django 5.2.12 on 2026-06-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sii', '0026_annualenterpriseregistermovement_warning_review_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualtaxreviewchecklist',
            name='review_decision_ref',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='annualtaxreviewchecklist',
            name='review_decision_state',
            field=models.CharField(choices=[('preparado_para_revision', 'Preparado para revision'), ('observado', 'Observado'), ('aprobado_para_presentacion', 'Aprobado para presentacion')], default='preparado_para_revision', max_length=32),
        ),
    ]
