# Generated by Codex on 2026-06-18

from django.db import migrations, models


def forwards(apps, schema_editor):
    AnnualTaxReviewChecklist = apps.get_model('sii', 'AnnualTaxReviewChecklist')
    AnnualTaxReviewChecklist.objects.filter(
        review_decision_state='preparado_para_revision',
    ).update(review_decision_state='preparado')


def backwards(apps, schema_editor):
    AnnualTaxReviewChecklist = apps.get_model('sii', 'AnnualTaxReviewChecklist')
    AnnualTaxReviewChecklist.objects.filter(
        review_decision_state='preparado',
    ).update(review_decision_state='preparado_para_revision')


class Migration(migrations.Migration):

    dependencies = [
        ('sii', '0027_annual_tax_review_decision'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name='annualtaxreviewchecklist',
            name='review_decision_state',
            field=models.CharField(choices=[('preparado', 'Preparado'), ('observado', 'Observado'), ('aprobado_para_presentacion', 'Aprobado para presentacion')], default='preparado', max_length=32),
        ),
    ]
