# Generated by Codex on 2026-06-18

import hashlib
import json

from django.db import migrations, models


def _payload_hash(value):
    return hashlib.sha256(
        json.dumps(value, sort_keys=True, separators=(',', ':'), ensure_ascii=True, default=str).encode('utf-8')
    ).hexdigest()


def forwards(apps, schema_editor):
    AnnualTaxReviewChecklist = apps.get_model('sii', 'AnnualTaxReviewChecklist')
    for checklist in AnnualTaxReviewChecklist.objects.all():
        evidence_ref = (
            checklist.review_decision_evidence_ref
            or f'annual-tax-review-decision-evidence-{checklist.empresa_id}-at{checklist.anio_tributario}-v1'
        )
        payload = checklist.review_payload if isinstance(checklist.review_payload, dict) else {}
        payload = dict(payload)
        payload['review_decision_ref'] = checklist.review_decision_ref
        payload['review_decision_evidence_ref'] = evidence_ref
        review_decision = payload.get('review_decision') if isinstance(payload.get('review_decision'), dict) else {}
        review_decision = dict(review_decision)
        review_decision['evidence_ref'] = evidence_ref
        payload['review_decision'] = review_decision
        checklist.review_decision_evidence_ref = evidence_ref
        checklist.review_payload = payload
        checklist.hash_checklist = _payload_hash(payload)
        checklist.save(update_fields=['review_decision_evidence_ref', 'review_payload', 'hash_checklist'])


def backwards(apps, schema_editor):
    AnnualTaxReviewChecklist = apps.get_model('sii', 'AnnualTaxReviewChecklist')
    for checklist in AnnualTaxReviewChecklist.objects.all():
        payload = checklist.review_payload if isinstance(checklist.review_payload, dict) else {}
        payload = dict(payload)
        payload.pop('review_decision_evidence_ref', None)
        review_decision = payload.get('review_decision') if isinstance(payload.get('review_decision'), dict) else {}
        review_decision = dict(review_decision)
        review_decision.pop('evidence_ref', None)
        payload['review_decision'] = review_decision
        checklist.review_payload = payload
        checklist.hash_checklist = _payload_hash(payload)
        checklist.save(update_fields=['review_payload', 'hash_checklist'])


class Migration(migrations.Migration):

    dependencies = [
        ('sii', '0028_annual_tax_review_prepared_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualtaxreviewchecklist',
            name='review_decision_evidence_ref',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(forwards, backwards),
    ]
