# Generated by Django 5.2.12 on 2026-03-16 23:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValorUFDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(unique=True)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('source_key', models.CharField(default='manual', max_length=64)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='AjusteContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_ajuste', models.CharField(max_length=64)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('moneda', models.CharField(choices=[('CLP', 'CLP'), ('UF', 'UF')], max_length=8)),
                ('mes_inicio', models.DateField()),
                ('mes_fin', models.DateField()),
                ('justificacion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_contrato', to='contratos.contrato')),
            ],
            options={
                'ordering': ['contrato_id', 'mes_inicio'],
            },
        ),
        migrations.CreateModel(
            name='GarantiaContractual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monto_pactado', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('monto_recibido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('monto_devuelto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('monto_aplicado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('estado_garantia', models.CharField(choices=[('pendiente_recepcion', 'Pendiente recepcion'), ('retenida', 'Retenida'), ('parcialmente_devuelta', 'Parcialmente devuelta'), ('devuelta', 'Devuelta'), ('aplicada', 'Aplicada')], default='pendiente_recepcion', max_length=32)),
                ('fecha_recepcion', models.DateField(blank=True, null=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='garantia_contractual', to='contratos.contrato')),
            ],
            options={
                'ordering': ['contrato_id'],
            },
        ),
        migrations.CreateModel(
            name='HistorialGarantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_movimiento', models.CharField(choices=[('deposito', 'Deposito'), ('devolucion_parcial', 'Devolucion parcial'), ('devolucion_total', 'Devolucion total'), ('retencion_parcial', 'Retencion parcial'), ('retencion_total', 'Retencion total')], max_length=32)),
                ('monto_clp', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha', models.DateField()),
                ('justificacion', models.TextField(blank=True)),
                ('garantia_contractual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_movimientos', to='cobranza.garantiacontractual')),
                ('movimiento_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_derivados', to='cobranza.historialgarantia')),
            ],
            options={
                'ordering': ['garantia_contractual_id', 'fecha', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PagoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('anio', models.PositiveSmallIntegerField()),
                ('monto_calculado_clp', models.DecimalField(decimal_places=2, max_digits=14)),
                ('monto_pagado_clp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_deposito_banco', models.DateField(blank=True, null=True)),
                ('fecha_deteccion_sistema', models.DateField(blank=True, null=True)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('atrasado', 'Atrasado'), ('en_repactacion', 'En repactacion'), ('pagado_via_repactacion', 'Pagado via repactacion'), ('pagado_por_acuerdo_termino', 'Pagado por acuerdo de termino'), ('condonado', 'Condonado')], default='pendiente', max_length=32)),
                ('dias_mora', models.PositiveIntegerField(default=0)),
                ('codigo_conciliacion_efectivo', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='El codigo de conciliacion efectivo debe tener exactamente 3 digitos.', regex='^\\d{3}$')])),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_mensuales', to='contratos.contrato')),
                ('periodo_contractual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_mensuales', to='contratos.periodocontractual')),
            ],
            options={
                'ordering': ['-anio', '-mes', 'contrato_id'],
                'constraints': [models.UniqueConstraint(fields=('contrato', 'anio', 'mes'), name='uniq_pago_mensual_por_contrato_periodo')],
            },
        ),
    ]
