# Generated by Django 5.2.12 on 2026-03-16 23:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0001_initial'),
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoCobroResidual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referencia_visible', models.CharField(max_length=10, unique=True)),
                ('saldo_actual', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada')], default='activa', max_length=16)),
                ('fecha_activacion', models.DateField()),
                ('arrendatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='codigos_cobro_residual', to='contratos.arrendatario')),
                ('contrato_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='codigos_cobro_residual', to='contratos.contrato')),
            ],
            options={
                'ordering': ['-fecha_activacion'],
            },
        ),
        migrations.CreateModel(
            name='EstadoCuentaArrendatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resumen_operativo', models.JSONField(blank=True, default=dict)),
                ('score_pago', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('arrendatario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado_cuenta', to='contratos.arrendatario')),
            ],
            options={
                'ordering': ['arrendatario_id'],
            },
        ),
        migrations.CreateModel(
            name='RepactacionDeuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deuda_total_original', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('cantidad_cuotas', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('monto_cuota', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('cumplida', 'Cumplida'), ('incumplida', 'Incumplida'), ('cancelada', 'Cancelada')], default='borrador', max_length=16)),
                ('arrendatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repactaciones_deuda', to='contratos.arrendatario')),
                ('contrato_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repactaciones_deuda', to='contratos.contrato')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
