# Generated by Django 5.2.12 on 2026-03-18 10:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0002_codigocobroresidual_estadocuentaarrendatario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagomensual',
            name='monto_facturable_clp',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
    ]
