# Generated by Django 5.2.12 on 2026-05-21 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0005_repair_legacy_distribuciones_and_add_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pagomensual',
            name='fecha_pago_webpay',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GateCobroExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capacidad_key', models.CharField(choices=[('WebPay.IntentoPago', 'WebPay intento de pago')], default='WebPay.IntentoPago', max_length=32)),
                ('provider_key', models.CharField(default='transbank_webpay', max_length=64)),
                ('estado_gate', models.CharField(choices=[('abierto', 'Abierto'), ('condicionado', 'Condicionado'), ('cerrado', 'Cerrado'), ('suspendido', 'Suspendido')], default='condicionado', max_length=16)),
                ('restricciones_operativas', models.JSONField(blank=True, default=dict)),
                ('evidencia_ref', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['capacidad_key', 'provider_key'],
                'constraints': [models.UniqueConstraint(fields=('capacidad_key', 'provider_key'), name='uniq_gate_cobro_externo_capacidad_provider')],
            },
        ),
        migrations.CreateModel(
            name='IntentoPagoWebPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_key', models.CharField(default='transbank_webpay', max_length=64)),
                ('monto_clp_snapshot', models.DecimalField(decimal_places=2, max_digits=14)),
                ('buy_order', models.CharField(blank=True, max_length=64)),
                ('session_id', models.CharField(blank=True, max_length=64)),
                ('return_url_ref', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('bloqueado_gate', 'Bloqueado por gate'), ('preparado', 'Preparado'), ('confirmado_manual_controlado', 'Confirmado manual controlado'), ('cancelado', 'Cancelado'), ('fallido', 'Fallido')], default='bloqueado_gate', max_length=32)),
                ('motivo_bloqueo', models.TextField(blank=True)),
                ('external_ref', models.CharField(blank=True, max_length=255)),
                ('fecha_pago_webpay', models.DateField(blank=True, null=True)),
                ('confirmado_at', models.DateTimeField(blank=True, null=True)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('gate_cobro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intentos_webpay', to='cobranza.gatecobroexterno')),
                ('pago_mensual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intentos_webpay', to='cobranza.pagomensual')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intentos_webpay', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'preparado')), fields=('pago_mensual',), name='uniq_intento_webpay_preparado_por_pago'), models.UniqueConstraint(condition=models.Q(('buy_order', ''), _negated=True), fields=('buy_order',), name='uniq_intento_webpay_buy_order_no_vacio')],
            },
        ),
    ]
