# Generated by Django 5.2.12 on 2026-05-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0006_pagomensual_fecha_pago_webpay_gatecobroexterno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garantiacontractual',
            name='aceptacion_parcial_ref',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
