# Generated by Django 5.2.12 on 2026-05-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0007_garantiacontractual_aceptacion_parcial_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='repactaciondeuda',
            name='excepcion_parcial_motivo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='repactaciondeuda',
            name='excepcion_parcial_ref',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
