# Generated by Django 5.2.12 on 2026-05-25 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0008_repactaciondeuda_excepcion_parcial_motivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagomensual',
            name='repactacion_deuda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_origen', to='cobranza.repactaciondeuda'),
        ),
    ]
