# Generated by Django 5.2.12 on 2026-05-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0009_pagomensual_repactacion_deuda'),
    ]

    operations = [
        migrations.AddField(
            model_name='garantiacontractual',
            name='resolucion_exceso_garantia',
            field=models.CharField(blank=True, choices=[('clasificar', 'Clasificar'), ('devolver', 'Devolver'), ('regularizar', 'Regularizar'), ('bloquear', 'Bloquear')], max_length=32),
        ),
        migrations.AddField(
            model_name='garantiacontractual',
            name='resolucion_exceso_garantia_motivo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='garantiacontractual',
            name='resolucion_exceso_garantia_ref',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
