# Generated by Django 5.2.12 on 2026-05-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0013_pagomensual_exceptional_resolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valorufdiario',
            name='source_key',
            field=models.CharField(choices=[('UF.BancoCentral', 'Banco Central'), ('UF.CMF', 'CMF'), ('UF.MiIndicador', 'MiIndicador'), ('UF.CargaManualExtraordinaria', 'Carga manual extraordinaria')], default='UF.CargaManualExtraordinaria', max_length=64),
        ),
    ]
