# Generated by Django 5.2.12 on 2026-05-27 16:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0014_valor_uf_canonical_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagomensual',
            name='moneda_calculo',
            field=models.CharField(choices=[('CLP', 'CLP'), ('UF', 'UF')], default='CLP', max_length=8),
        ),
        migrations.AddField(
            model_name='pagomensual',
            name='uf_fecha_usada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagomensual',
            name='uf_source_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='pagomensual',
            name='uf_valor_usado',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
    ]
