from django.urls import path

from .views import (
    AjusteContratoDetailView,
    AjusteContratoListCreateView,
    CobranzaSnapshotView,
    CodigoCobroResidualDetailView,
    CodigoCobroResidualListCreateView,
    DistribucionCobroMensualDetailView,
    DistribucionCobroMensualListView,
    EstadoCuentaArrendatarioDetailView,
    EstadoCuentaArrendatarioListView,
    EstadoCuentaArrendatarioRebuildView,
    GarantiaContractualDetailView,
    GarantiaContractualListCreateView,
    GarantiaMovimientoCreateView,
    HistorialGarantiaDetailView,
    HistorialGarantiaListView,
    PagoMensualDetailView,
    PagoMensualGenerateView,
    PagoMensualListView,
    RepactacionDeudaDetailView,
    RepactacionDeudaListCreateView,
    ValorUFDiarioDetailView,
    ValorUFDiarioListCreateView,
)

urlpatterns = [
    path('snapshot/', CobranzaSnapshotView.as_view(), name='cobranza-snapshot'),
    path('valores-uf/', ValorUFDiarioListCreateView.as_view(), name='cobranza-valor-uf-list'),
    path('valores-uf/<int:pk>/', ValorUFDiarioDetailView.as_view(), name='cobranza-valor-uf-detail'),
    path('ajustes-contrato/', AjusteContratoListCreateView.as_view(), name='cobranza-ajuste-list'),
    path('ajustes-contrato/<int:pk>/', AjusteContratoDetailView.as_view(), name='cobranza-ajuste-detail'),
    path('pagos-mensuales/', PagoMensualListView.as_view(), name='cobranza-pago-list'),
    path('pagos-mensuales/generar/', PagoMensualGenerateView.as_view(), name='cobranza-pago-generate'),
    path('pagos-mensuales/<int:pk>/', PagoMensualDetailView.as_view(), name='cobranza-pago-detail'),
    path('pagos-mensuales/distribuciones/', DistribucionCobroMensualListView.as_view(), name='cobranza-distribucion-list'),
    path('pagos-mensuales/distribuciones/<int:pk>/', DistribucionCobroMensualDetailView.as_view(), name='cobranza-distribucion-detail'),
    path('garantias/', GarantiaContractualListCreateView.as_view(), name='cobranza-garantia-list'),
    path('garantias/<int:pk>/', GarantiaContractualDetailView.as_view(), name='cobranza-garantia-detail'),
    path('garantias/<int:pk>/movimientos/', GarantiaMovimientoCreateView.as_view(), name='cobranza-garantia-movimiento'),
    path('historial-garantias/', HistorialGarantiaListView.as_view(), name='cobranza-historial-list'),
    path('historial-garantias/<int:pk>/', HistorialGarantiaDetailView.as_view(), name='cobranza-historial-detail'),
    path('repactaciones/', RepactacionDeudaListCreateView.as_view(), name='cobranza-repactacion-list'),
    path('repactaciones/<int:pk>/', RepactacionDeudaDetailView.as_view(), name='cobranza-repactacion-detail'),
    path('codigos-residuales/', CodigoCobroResidualListCreateView.as_view(), name='cobranza-residual-list'),
    path('codigos-residuales/<int:pk>/', CodigoCobroResidualDetailView.as_view(), name='cobranza-residual-detail'),
    path('estados-cuenta/', EstadoCuentaArrendatarioListView.as_view(), name='cobranza-estado-cuenta-list'),
    path('estados-cuenta/<int:pk>/', EstadoCuentaArrendatarioDetailView.as_view(), name='cobranza-estado-cuenta-detail'),
    path('estados-cuenta/recalcular/', EstadoCuentaArrendatarioRebuildView.as_view(), name='cobranza-estado-cuenta-rebuild'),
]
