from django.urls import path

from .views import (
    AsientoContableDetailView,
    AsientoContableListView,
    BalanceComprobacionListView,
    CierreMensualApproveView,
    CierreMensualContableDetailView,
    CierreMensualContableListView,
    CierreMensualPrepareView,
    CierreMensualReopenView,
    ConfiguracionFiscalEmpresaDetailView,
    ConfiguracionFiscalEmpresaListCreateView,
    ControlSnapshotView,
    CuentaContableDetailView,
    CuentaContableListCreateView,
    EventoContableDetailView,
    EventoContableListCreateView,
    EventoContablePostView,
    LibroDiarioListView,
    LibroMayorListView,
    MatrizReglasContablesDetailView,
    MatrizReglasContablesListCreateView,
    ObligacionTributariaMensualListView,
    PoliticaReversoContableDetailView,
    PoliticaReversoContableListCreateView,
    RegimenTributarioEmpresaDetailView,
    RegimenTributarioEmpresaListCreateView,
    ReglaContableDetailView,
    ReglaContableListCreateView,
)

urlpatterns = [
    path('snapshot/', ControlSnapshotView.as_view(), name='contabilidad-snapshot'),
    path('regimenes-tributarios/', RegimenTributarioEmpresaListCreateView.as_view(), name='contabilidad-regimen-list'),
    path('regimenes-tributarios/<int:pk>/', RegimenTributarioEmpresaDetailView.as_view(), name='contabilidad-regimen-detail'),
    path('configuraciones-fiscales/', ConfiguracionFiscalEmpresaListCreateView.as_view(), name='contabilidad-config-list'),
    path('configuraciones-fiscales/<int:pk>/', ConfiguracionFiscalEmpresaDetailView.as_view(), name='contabilidad-config-detail'),
    path('cuentas-contables/', CuentaContableListCreateView.as_view(), name='contabilidad-cuenta-list'),
    path('cuentas-contables/<int:pk>/', CuentaContableDetailView.as_view(), name='contabilidad-cuenta-detail'),
    path('reglas-contables/', ReglaContableListCreateView.as_view(), name='contabilidad-regla-list'),
    path('reglas-contables/<int:pk>/', ReglaContableDetailView.as_view(), name='contabilidad-regla-detail'),
    path('matriz-reglas/', MatrizReglasContablesListCreateView.as_view(), name='contabilidad-matriz-list'),
    path('matriz-reglas/<int:pk>/', MatrizReglasContablesDetailView.as_view(), name='contabilidad-matriz-detail'),
    path('eventos-contables/', EventoContableListCreateView.as_view(), name='contabilidad-evento-list'),
    path('eventos-contables/<int:pk>/', EventoContableDetailView.as_view(), name='contabilidad-evento-detail'),
    path('eventos-contables/<int:pk>/contabilizar/', EventoContablePostView.as_view(), name='contabilidad-evento-post'),
    path('asientos-contables/', AsientoContableListView.as_view(), name='contabilidad-asiento-list'),
    path('asientos-contables/<int:pk>/', AsientoContableDetailView.as_view(), name='contabilidad-asiento-detail'),
    path('politicas-reverso/', PoliticaReversoContableListCreateView.as_view(), name='contabilidad-reverso-list'),
    path('politicas-reverso/<int:pk>/', PoliticaReversoContableDetailView.as_view(), name='contabilidad-reverso-detail'),
    path('obligaciones-mensuales/', ObligacionTributariaMensualListView.as_view(), name='contabilidad-obligacion-list'),
    path('libro-diario/', LibroDiarioListView.as_view(), name='contabilidad-libro-diario-list'),
    path('libro-mayor/', LibroMayorListView.as_view(), name='contabilidad-libro-mayor-list'),
    path('balance-comprobacion/', BalanceComprobacionListView.as_view(), name='contabilidad-balance-list'),
    path('cierres-mensuales/', CierreMensualContableListView.as_view(), name='contabilidad-cierre-list'),
    path('cierres-mensuales/<int:pk>/', CierreMensualContableDetailView.as_view(), name='contabilidad-cierre-detail'),
    path('cierres-mensuales/preparar/', CierreMensualPrepareView.as_view(), name='contabilidad-cierre-prepare'),
    path('cierres-mensuales/<int:pk>/aprobar/', CierreMensualApproveView.as_view(), name='contabilidad-cierre-approve'),
    path('cierres-mensuales/<int:pk>/reabrir/', CierreMensualReopenView.as_view(), name='contabilidad-cierre-reopen'),
]
