# Generated by Django 5.2.12 on 2026-03-16 19:07

import django.db.models.deletion
import django.utils.timezone
import patrimonio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patrimonio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaRecaudadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institucion', models.CharField(max_length=120)),
                ('numero_cuenta', models.CharField(max_length=64)),
                ('tipo_cuenta', models.CharField(max_length=64)),
                ('titular_nombre', models.CharField(max_length=255)),
                ('titular_rut', models.CharField(max_length=16, validators=[patrimonio.validators.validate_rut])),
                ('moneda_operativa', models.CharField(choices=[('CLP', 'CLP'), ('UF', 'UF')], default='CLP', max_length=8)),
                ('estado_operativo', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('pausada', 'Pausada'), ('inactiva', 'Inactiva')], default='borrador', max_length=16)),
                ('empresa_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_recaudadoras', to='patrimonio.empresa')),
                ('socio_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_recaudadoras', to='patrimonio.socio')),
            ],
            options={
                'ordering': ['institucion', 'numero_cuenta'],
            },
        ),
        migrations.CreateModel(
            name='IdentidadDeEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canal', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=16)),
                ('remitente_visible', models.CharField(max_length=255)),
                ('direccion_o_numero', models.CharField(max_length=255)),
                ('credencial_ref', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('suspendida', 'Suspendida'), ('inactiva', 'Inactiva')], default='borrador', max_length=16)),
                ('empresa_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='identidades_envio', to='patrimonio.empresa')),
                ('socio_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='identidades_envio', to='patrimonio.socio')),
            ],
            options={
                'ordering': ['canal', 'remitente_visible'],
            },
        ),
        migrations.CreateModel(
            name='MandatoOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_relacion_operativa', models.CharField(max_length=64)),
                ('autoriza_recaudacion', models.BooleanField(default=False)),
                ('autoriza_facturacion', models.BooleanField(default=False)),
                ('autoriza_comunicacion', models.BooleanField(default=False)),
                ('vigencia_desde', models.DateField(default=django.utils.timezone.localdate)),
                ('vigencia_hasta', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('inactiva', 'Inactiva')], default='borrador', max_length=16)),
                ('administrador_empresa_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mandatos_como_administradora', to='patrimonio.empresa')),
                ('administrador_socio_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mandatos_como_administrador', to='patrimonio.socio')),
                ('cuenta_recaudadora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mandatos_operacion', to='operacion.cuentarecaudadora')),
                ('entidad_facturadora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mandatos_como_facturadora', to='patrimonio.empresa')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mandatos_operacion', to='patrimonio.propiedad')),
                ('propietario_comunidad_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mandatos_como_propietaria', to='patrimonio.comunidadpatrimonial')),
                ('propietario_empresa_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mandatos_como_propietaria', to='patrimonio.empresa')),
                ('propietario_socio_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mandatos_como_propietario', to='patrimonio.socio')),
            ],
            options={
                'ordering': ['propiedad__codigo_propiedad', '-vigencia_desde'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionCanalOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canal', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=16)),
                ('prioridad', models.PositiveSmallIntegerField(default=1)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=16)),
                ('identidad_envio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_operacion', to='operacion.identidaddeenvio')),
                ('mandato_operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_canal', to='operacion.mandatooperacion')),
            ],
            options={
                'ordering': ['mandato_operacion_id', 'canal', 'prioridad'],
            },
        ),
        migrations.AddConstraint(
            model_name='cuentarecaudadora',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('empresa_owner__isnull', False), ('socio_owner__isnull', True)), models.Q(('empresa_owner__isnull', True), ('socio_owner__isnull', False)), _connector='OR'), name='cuenta_recaudadora_exactly_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='cuentarecaudadora',
            constraint=models.UniqueConstraint(fields=('institucion', 'numero_cuenta'), name='uniq_cuenta_recaudadora_por_institucion_numero'),
        ),
        migrations.AddConstraint(
            model_name='identidaddeenvio',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('empresa_owner__isnull', False), ('socio_owner__isnull', True)), models.Q(('empresa_owner__isnull', True), ('socio_owner__isnull', False)), _connector='OR'), name='identidad_envio_exactly_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='identidaddeenvio',
            constraint=models.UniqueConstraint(fields=('canal', 'direccion_o_numero'), name='uniq_identidad_envio_por_canal_direccion'),
        ),
        migrations.AddConstraint(
            model_name='mandatooperacion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('propietario_comunidad_owner__isnull', True), ('propietario_empresa_owner__isnull', False), ('propietario_socio_owner__isnull', True)), models.Q(('propietario_comunidad_owner__isnull', False), ('propietario_empresa_owner__isnull', True), ('propietario_socio_owner__isnull', True)), models.Q(('propietario_comunidad_owner__isnull', True), ('propietario_empresa_owner__isnull', True), ('propietario_socio_owner__isnull', False)), _connector='OR'), name='mandato_exactly_one_propietario'),
        ),
        migrations.AddConstraint(
            model_name='mandatooperacion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('administrador_empresa_owner__isnull', False), ('administrador_socio_owner__isnull', True)), models.Q(('administrador_empresa_owner__isnull', True), ('administrador_socio_owner__isnull', False)), _connector='OR'), name='mandato_exactly_one_administrador'),
        ),
        migrations.AddConstraint(
            model_name='mandatooperacion',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'activa')), fields=('propiedad',), name='uniq_mandato_operacion_activo_por_propiedad'),
        ),
        migrations.AddConstraint(
            model_name='asignacioncanaloperacion',
            constraint=models.UniqueConstraint(fields=('mandato_operacion', 'canal', 'prioridad'), name='uniq_asignacion_canal_prioridad_por_mandato'),
        ),
    ]
