# Generated by Django 5.2.12 on 2026-05-21 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0002_recaudador_en_mandato_operacion'),
        ('patrimonio', '0003_repair_legacy_representacion_modes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cuentarecaudadora',
            name='cuenta_recaudadora_exactly_one_owner',
        ),
        migrations.RemoveConstraint(
            model_name='mandatooperacion',
            name='mandato_exactly_one_recaudador',
        ),
        migrations.AddField(
            model_name='cuentarecaudadora',
            name='comunidad_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_recaudadoras', to='patrimonio.comunidadpatrimonial'),
        ),
        migrations.AddField(
            model_name='mandatooperacion',
            name='recaudador_comunidad_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mandatos_como_recaudadora', to='patrimonio.comunidadpatrimonial'),
        ),
        migrations.AddConstraint(
            model_name='cuentarecaudadora',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('comunidad_owner__isnull', True), ('empresa_owner__isnull', False), ('socio_owner__isnull', True)), models.Q(('comunidad_owner__isnull', False), ('empresa_owner__isnull', True), ('socio_owner__isnull', True)), models.Q(('comunidad_owner__isnull', True), ('empresa_owner__isnull', True), ('socio_owner__isnull', False)), _connector='OR'), name='cuenta_recaudadora_exactly_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='mandatooperacion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('recaudador_comunidad_owner__isnull', True), ('recaudador_empresa_owner__isnull', False), ('recaudador_socio_owner__isnull', True)), models.Q(('recaudador_comunidad_owner__isnull', False), ('recaudador_empresa_owner__isnull', True), ('recaudador_socio_owner__isnull', True)), models.Q(('recaudador_comunidad_owner__isnull', True), ('recaudador_empresa_owner__isnull', True), ('recaudador_socio_owner__isnull', False)), _connector='OR'), name='mandato_exactly_one_recaudador'),
        ),
    ]
