# Generated by Django 5.2.12 on 2026-05-24 18:33

import patrimonio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0003_comunidad_recaudadora'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandatooperacion',
            name='autoridad_operativa_evidencia_ref',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mandatooperacion',
            name='autoridad_operativa_nombre',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mandatooperacion',
            name='autoridad_operativa_rut',
            field=models.CharField(blank=True, max_length=16, validators=[patrimonio.validators.validate_rut]),
        ),
    ]
