# Generated by Django 5.2.12 on 2026-05-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0005_remove_mandatooperacion_unique_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentarecaudadora',
            name='evidencia_operativa_ref',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cuentarecaudadora',
            name='modo_operativo',
            field=models.CharField(blank=True, choices=[('manual_controlado', 'Manual controlado'), ('gate_bancario', 'Gate bancario')], max_length=32),
        ),
        migrations.AddField(
            model_name='cuentarecaudadora',
            name='uso_operativo',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
