# Generated by Django 5.2.12 on 2026-05-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualresolution',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('superseded', 'Superseded')], default='open', max_length=20),
        ),
    ]
