# Generated by Django 5.2.12 on 2026-05-22 01:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalRuntimeSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_key', models.CharField(choices=[('monthly_calculation_latency', 'Latencia de calculo mensual'), ('queue_runtime', 'Colas y tareas'), ('failed_webhooks', 'Webhooks fallidos'), ('failed_crons', 'Crons fallidos')], max_length=64, unique=True)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('attention', 'Atencion'), ('missing', 'Faltante')], default='missing', max_length=16)),
                ('source_kind', models.CharField(choices=[('local', 'Local'), ('fixture', 'Fixture'), ('demo', 'Demo'), ('snapshot_controlado', 'Snapshot controlado'), ('real_autorizado', 'Real autorizado')], default='local', max_length=32)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('evidence_ref', models.CharField(blank=True, max_length=255)),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['signal_key'],
            },
        ),
    ]
