# Generated by Django 5.2.12 on 2026-05-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_operationalruntimesignal'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalruntimesignal',
            name='authorization_ref',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='operationalruntimesignal',
            name='source_label',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
