# Generated by Django 5.2.12 on 2026-03-18 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticaFirmaYNotaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_documental', models.CharField(choices=[('contrato_principal', 'Contrato principal'), ('anexo', 'Anexo'), ('carta_aviso', 'Carta de aviso'), ('liquidacion_garantia', 'Liquidacion de garantia'), ('respaldo_tributario', 'Respaldo tributario'), ('comprobante_notarial', 'Comprobante notarial'), ('evidencia_resolucion_manual', 'Evidencia de resolucion manual')], max_length=64, unique=True)),
                ('requiere_firma_arrendador', models.BooleanField(default=False)),
                ('requiere_firma_arrendatario', models.BooleanField(default=False)),
                ('requiere_codeudor', models.BooleanField(default=False)),
                ('requiere_notaria', models.BooleanField(default=False)),
                ('modo_firma_permitido', models.CharField(choices=[('firma_simple', 'Firma simple'), ('firma_avanzada', 'Firma avanzada'), ('mixta', 'Mixta'), ('manual', 'Manual')], default='firma_simple', max_length=32)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=16)),
            ],
            options={
                'ordering': ['tipo_documental'],
            },
        ),
        migrations.CreateModel(
            name='ExpedienteDocumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entidad_tipo', models.CharField(max_length=64)),
                ('entidad_id', models.CharField(max_length=64)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado'), ('archivado', 'Archivado')], default='abierto', max_length=16)),
                ('owner_operativo', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['entidad_tipo', 'entidad_id'],
                'constraints': [models.UniqueConstraint(fields=('entidad_tipo', 'entidad_id'), name='uniq_expediente_por_entidad')],
            },
        ),
        migrations.CreateModel(
            name='DocumentoEmitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_documental', models.CharField(choices=[('contrato_principal', 'Contrato principal'), ('anexo', 'Anexo'), ('carta_aviso', 'Carta de aviso'), ('liquidacion_garantia', 'Liquidacion de garantia'), ('respaldo_tributario', 'Respaldo tributario'), ('comprobante_notarial', 'Comprobante notarial'), ('evidencia_resolucion_manual', 'Evidencia de resolucion manual')], max_length=64)),
                ('version_plantilla', models.CharField(max_length=64)),
                ('checksum', models.CharField(max_length=128)),
                ('fecha_carga', models.DateTimeField()),
                ('origen', models.CharField(choices=[('generado_sistema', 'Generado por sistema'), ('carga_externa_controlada', 'Carga externa controlada')], max_length=32)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('emitido', 'Emitido'), ('formalizado', 'Formalizado'), ('archivado', 'Archivado'), ('cancelado', 'Cancelado')], default='borrador', max_length=16)),
                ('storage_ref', models.CharField(max_length=255)),
                ('firma_arrendador_registrada', models.BooleanField(default=False)),
                ('firma_arrendatario_registrada', models.BooleanField(default=False)),
                ('firma_codeudor_registrada', models.BooleanField(default=False)),
                ('recepcion_notarial_registrada', models.BooleanField(default=False)),
                ('comprobante_notarial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_formalizados', to='documentos.documentoemitido')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_emitidos', to=settings.AUTH_USER_MODEL)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_emitidos', to='documentos.expedientedocumental')),
            ],
            options={
                'ordering': ['-fecha_carga', '-id'],
            },
        ),
    ]
