# Generated by Django 5.2.12 on 2026-05-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicafirmaynotaria',
            name='requiere_estado_civil_arrendatario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='politicafirmaynotaria',
            name='requiere_nacionalidad_arrendatario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='politicafirmaynotaria',
            name='requiere_profesion_arrendatario',
            field=models.BooleanField(default=False),
        ),
    ]
