# Generated by Django 5.2.12 on 2026-05-24 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_politicafirmaynotaria_requiere_estado_civil_arrendatario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoemitido',
            name='correccion_ref',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='documentoemitido',
            name='documento_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='versiones_correctivas', to='documentos.documentoemitido'),
        ),
    ]
