# Generated by Django 5.2.12 on 2026-05-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_documentoemitido_correccion_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoemitido',
            name='evidencia_formalizacion_ref',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
