# Generated by Django 5.2.12 on 2026-05-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_documentoemitido_evidencia_formalizacion_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaDocumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_documental', models.CharField(choices=[('contrato_principal', 'Contrato principal'), ('anexo', 'Anexo'), ('carta_aviso', 'Carta de aviso'), ('liquidacion_garantia', 'Liquidacion de garantia'), ('respaldo_tributario', 'Respaldo tributario'), ('comprobante_notarial', 'Comprobante notarial'), ('evidencia_resolucion_manual', 'Evidencia de resolucion manual')], max_length=64)),
                ('version_plantilla', models.CharField(max_length=64)),
                ('plantilla_ref', models.CharField(max_length=255)),
                ('checksum_plantilla', models.CharField(max_length=128)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=16)),
            ],
            options={
                'ordering': ['tipo_documental', 'version_plantilla'],
                'constraints': [models.UniqueConstraint(fields=('tipo_documental', 'version_plantilla'), name='uniq_plantilla_documental_version')],
            },
        ),
    ]
