# Generated by Django 5.2.12 on 2026-06-26 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_plantilladocumental'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video'), ('planilla', 'Planilla'), ('texto', 'Texto'), ('documento_fuente', 'Documento fuente'), ('comprimido', 'Comprimido'), ('evidencia_operacional', 'Evidencia operacional'), ('otro', 'Otro')], max_length=32)),
                ('subcategoria', models.CharField(blank=True, max_length=64)),
                ('titulo_operativo', models.CharField(max_length=255)),
                ('descripcion_objetiva', models.TextField(blank=True)),
                ('extension', models.CharField(max_length=16)),
                ('mime_type', models.CharField(blank=True, max_length=128)),
                ('checksum_sha256', models.CharField(max_length=128)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('storage_ref', models.CharField(max_length=255)),
                ('origen_auditoria', models.CharField(max_length=128)),
                ('estado_clasificacion', models.CharField(choices=[('confirmado', 'Confirmado'), ('probable', 'Probable'), ('requiere_revision_manual', 'Requiere revision manual'), ('duplicado_exactamente', 'Duplicado exactamente'), ('alias_de_canonico', 'Alias de canonico'), ('no_cargable_sin_decision', 'No cargable sin decision')], default='confirmado', max_length=32)),
                ('fecha_archivo', models.DateTimeField(blank=True, null=True)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duplicados', to='documentos.archivoexpediente')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_expediente', to='documentos.expedientedocumental')),
            ],
            options={
                'ordering': ['expediente_id', 'categoria', 'subcategoria', 'titulo_operativo', 'id'],
                'indexes': [models.Index(fields=['checksum_sha256'], name='idx_archivo_exp_checksum'), models.Index(fields=['categoria', 'estado_clasificacion'], name='idx_archivo_exp_cat_estado')],
            },
        ),
    ]
